import { enqueueEmail } from "@/lib/email-queue";
import { renderEmailLayout, escapeHtml } from "@/lib/email-layout";
import { prisma } from "@/lib/prisma";
import { sendWhatsAppNotification, customerOrderWhatsAppMessage, vendorFirstOrderWhatsAppMessage } from "@/lib/whatsapp-notifications";

export async function sendEmail(opts: { to: string; subject: string; html: string; event?: string }) {
  const result = await enqueueEmail({ to: opts.to, subject: opts.subject, html: opts.html, event: opts.event ?? "generic" });
  if (opts.event === "order_confirmation") {
    void (async () => {
      const user = await prisma.user.findUnique({ where: { email: opts.to }, select: { phone: true } });
      const match = opts.subject.match(/^Order (.+) confirmed$/);
      if (!user?.phone || !match) return;
      const order = await prisma.order.findUnique({ where: { orderNumber: match[1] }, select: { totalAmount: true } });
      if (!order) return;
      await sendWhatsAppNotification({ to: user.phone, message: customerOrderWhatsAppMessage(match[1], Number(order.totalAmount)), event: "customer_order_confirmed" });
    })().catch(() => undefined);
  }
  if (opts.event === "vendor_new_order") {
    void (async () => {
      const vendorUser = await prisma.user.findUnique({ where: { email: opts.to }, select: { phone: true, vendorProfile: { select: { id: true } } } });
      const match = opts.subject.match(/^New order — (.+)$/);
      if (!vendorUser?.vendorProfile || !match) return;
      const paidOrderCount = await prisma.vendorOrder.count({ where: { vendorId: vendorUser.vendorProfile.id, order: { paymentStatus: "PAID" } } });
      if (paidOrderCount !== 1) return;
      const order = await prisma.order.findUnique({ where: { orderNumber: match[1] }, select: { id: true, totalAmount: true } });
      if (!order) return;
      const vendorOrder = await prisma.vendorOrder.findFirst({ where: { orderId: order.id, vendorId: vendorUser.vendorProfile.id }, select: { items: { select: { quantity: true } } } });
      const itemCount = vendorOrder?.items.reduce((sum, item) => sum + item.quantity, 0) ?? 0;
      void enqueueEmail({ to: opts.to, ...vendorFirstOrderEmail(match[1], itemCount, Number(order.totalAmount)) });
      if (vendorUser.phone) void sendWhatsAppNotification({ to: vendorUser.phone, message: vendorFirstOrderWhatsAppMessage(match[1], Number(order.totalAmount)), event: "vendor_first_order" });
    })().catch(() => undefined);
  }
  return result;
}

export function verificationEmail(name: string, verifyUrl: string) { return { subject: "Verify your TTFL Store email", html: renderEmailLayout({ heading: "Confirm your email", previewText: "One click to finish setting up your TTFL Store account.", bodyHtml: `<p>Hi ${escapeHtml(name)},</p><p>Confirm your email to finish setting up your TTFL Store account.</p>`, ctaText: "Verify email", ctaUrl: verifyUrl }), event: "email_verification" }; }
export function passwordResetEmail(name: string, resetUrl: string) { return { subject: "Reset your TTFL Store password", html: renderEmailLayout({ heading: "Reset your password", previewText: "Reset your TTFL Store password.", bodyHtml: `<p>Hi ${escapeHtml(name)},</p><p>Use the button below to reset your password. If you didn't request this, you can safely ignore this email.</p>`, ctaText: "Reset password", ctaUrl: resetUrl }), event: "password_reset" }; }
export function vendorApplicationReceivedEmail(storeName: string) { return { subject: "We've received your vendor application", html: renderEmailLayout({ heading: "Application received", bodyHtml: `<p>Thanks for applying to sell as <strong>${escapeHtml(storeName)}</strong> on TTFL Store. Our team will review your application shortly — you'll get an email as soon as there's a decision.</p>` }), event: "vendor_application_received" }; }
export function orderConfirmationEmail(orderNumber: string) { return { subject: `Order ${orderNumber} confirmed`, html: renderEmailLayout({ heading: "Order confirmed", previewText: `We've received your payment for ${orderNumber}.`, bodyHtml: `<p>Thanks for your order! We've received your payment for <strong>${escapeHtml(orderNumber)}</strong>. The vendor(s) have been notified and will begin processing shortly.</p>` }), event: "order_confirmation" }; }
export function vendorNewOrderEmail(orderNumber: string, itemCount: number) { return { subject: `New order — ${orderNumber}`, html: renderEmailLayout({ heading: "New order", bodyHtml: `<p>You have a new order (<strong>${escapeHtml(orderNumber)}</strong>) with ${itemCount} item(s). Log in to your vendor dashboard to process it.</p>` }), event: "vendor_new_order" }; }
export function vendorFirstProductEmail(storeName: string, productName: string, productUrl: string) { return { subject: "🎉 Your first product is live on TTFL Store", html: renderEmailLayout({ heading: "Your first product is live!", previewText: "Congratulations — your store is officially open for business.", bodyHtml: `<p>Congratulations! <strong>${escapeHtml(productName)}</strong> is now live on TTFL Store.</p><p>Your store <strong>${escapeHtml(storeName)}</strong> is officially open for customers. This is your first live product — now let's get your next one listed.</p>`, ctaText: "View product", ctaUrl: productUrl }), event: "vendor_first_product" }; }
export function vendorFirstOrderEmail(orderNumber: string, itemCount: number, amount: number) { return { subject: "🎉 Congratulations on your first TTFL Store order", html: renderEmailLayout({ heading: "Your first order!", previewText: "Congratulations — you received your first order on TTFL Store.", bodyHtml: `<p>Congratulations! Your store has received its first order on TTFL Store.</p><p><strong>Order:</strong> ${escapeHtml(orderNumber)}<br><strong>Items:</strong> ${itemCount}<br><strong>Order value:</strong> ₦${amount.toLocaleString()}</p><p>Log in to your vendor dashboard to review and fulfill the order.</p>`, ctaText: "View orders", ctaUrl: `${process.env.APP_URL ?? "https://ttflstore.name.ng"}/vendor/dashboard/orders` }), event: "vendor_first_order" }; }
export function vendorApprovedEmail(storeName: string) { return { subject: "Your TTFL Store vendor application was approved", html: renderEmailLayout({ heading: "You're approved!", bodyHtml: `<p>Good news — <strong>${escapeHtml(storeName)}</strong> is now live on TTFL Store. You can start listing products right away.</p>` }), event: "vendor_approved" }; }
export function vendorRejectedEmail(storeName: string, reason: string) { return { subject: "Update on your TTFL Store vendor application", html: renderEmailLayout({ heading: "Application update", bodyHtml: `<p>Your application for <strong>${escapeHtml(storeName)}</strong> wasn't approved this time.</p><p><strong>Reason:</strong> ${escapeHtml(reason)}</p>` }), event: "vendor_rejected" }; }
export function adminNewVendorEmail(storeName: string) { return { subject: `New vendor application: ${storeName}`, html: renderEmailLayout({ heading: "New vendor application", bodyHtml: `<p><strong>${escapeHtml(storeName)}</strong> has applied to sell on TTFL Store. Review it in the admin dashboard.</p>` }), event: "admin_new_vendor" }; }
export function adminNewOrderEmail(orderNumber: string, totalAmount: number) { return { subject: `New order: ${orderNumber}`, html: renderEmailLayout({ heading: "New order placed", bodyHtml: `<p>A new order (<strong>${escapeHtml(orderNumber)}</strong>) was placed for ₦${totalAmount.toLocaleString()}.</p>` }), event: "admin_new_order" }; }
export function adminAccessGrantedEmail(name: string, email: string, adminUrl: string) { const displayName = name.trim() || "there"; const safeEmail = escapeHtml(email); const safeAdminUrl = escapeHtml(adminUrl); return { subject: "You now have admin access to TTFL Store", html: renderEmailLayout({ heading: "You're now a TTFL Store administrator", previewText: "Your TTFL Store account has been granted administrator access.", bodyHtml: `<p>Hi ${escapeHtml(displayName)},</p><p>Your existing TTFL Store account (<strong>${safeEmail}</strong>) has been granted <strong>Administrator</strong> access.</p><p><strong>Quick guide</strong></p><ol><li>Open the Admin Portal using the button below.</li><li>Sign in with your existing TTFL Store account.</li><li>Use the dashboard to manage vendors, products, orders, payouts, coupons, featured listings, support, broadcasts, analytics, and audit logs.</li><li>Only perform actions you are authorized to make, and always protect your account credentials.</li></ol><p>If you did not expect this change, contact the TTFL Store owner or platform administrator immediately.</p><p style="font-size:12px;color:#5B6472;word-break:break-all;">Admin Portal: ${safeAdminUrl}</p>`, ctaText: "Open Admin Portal", ctaUrl: adminUrl }), event: "admin_access_granted" }; }
export function vendorStaffInvitationEmail(storeName: string, role: string, inviteUrl: string) { return { subject: `You're invited to help manage ${storeName} on TTFL Store`, html: renderEmailLayout({ heading: "You're invited to join a TTFL Store team", previewText: `You've been invited to manage ${storeName} as ${role}.`, bodyHtml: `<p>You've been invited to help manage <strong>${escapeHtml(storeName)}</strong> on TTFL Store.</p><p>Your team role is <strong>${escapeHtml(role)}</strong>. Your access is limited to the permissions assigned to this role.</p><p>The invitation expires in 7 days. If you weren't expecting this invitation, you can ignore it.</p>`, ctaText: "Accept invitation", ctaUrl: inviteUrl }), event: "vendor_staff_invitation" }; }
export function payoutApprovedEmail(amount: number) { return { subject: "Your payout request was approved", html: renderEmailLayout({ heading: "Payout approved", bodyHtml: `<p>Your payout of ₦${amount.toLocaleString()} was approved and will be transferred shortly.</p>` }), event: "vendor_payout_approved" }; }
export function orderRefundedEmail(orderNumber: string) { return { subject: `Order ${orderNumber} refunded`, html: renderEmailLayout({ heading: "Order refunded", bodyHtml: `<p>Your order <strong>${escapeHtml(orderNumber)}</strong> has been refunded. The funds should reflect in 5-10 business days, depending on your bank.</p>` }), event: "order_refunded" }; }
