import { prisma } from "@/lib/prisma";
import { AppError } from "@/utils/app-error";
import { getVendorProfileForUser } from "@/lib/vendor-access";

export const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"] as const;
export type StoreHour={dayOfWeek:number;day:string;isOpen:boolean;openTime:string|null;closeTime:string|null};

let ready=false;
async function ensureReady(){if(ready)return;await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS store_business_hours (vendor_id TEXT NOT NULL REFERENCES vendor_profiles(id) ON DELETE CASCADE,day_of_week SMALLINT NOT NULL,is_open BOOLEAN NOT NULL DEFAULT TRUE,open_time TIME,close_time TIME,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(vendor_id,day_of_week),CHECK(day_of_week BETWEEN 0 AND 6),CHECK((is_open=FALSE) OR (open_time IS NOT NULL AND close_time IS NOT NULL)))`);ready=true;}
function normalizeInputTime(value:string|null):string|null{if(value==null||value==="")return null;const trimmed=value.trim();const match24=trimmed.match(/^(\d{1,2}):(\d{2})(?::\d{2}(?:\.\d+)?)?$/);if(match24){const hour=Number(match24[1]);const minute=Number(match24[2]);if(hour<=23&&minute<=59)return String(hour).padStart(2,"0")+":"+String(minute).padStart(2,"0");}const match12=trimmed.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);if(match12){let hour=Number(match12[1]);const minute=Number(match12[2]);const meridiem=match12[3].toUpperCase();if(hour>=1&&hour<=12&&minute<=59){if(hour===12)hour=0;if(meridiem==="PM")hour+=12;return String(hour).padStart(2,"0")+":"+String(minute).padStart(2,"0");}}return null;}
function normalize(rows:any[]):StoreHour[]{const map=new Map(rows.map(r=>[Number(r.dayOfWeek),r]));return DAYS.map((day,dayOfWeek)=>{const r=map.get(dayOfWeek);return{dayOfWeek,day,isOpen:r?.isOpen??false,openTime:r?.openTime?.slice(0,5)??null,closeTime:r?.closeTime?.slice(0,5)??null};});}
export async function getHours(vendorId:string){await ensureReady();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT day_of_week AS "dayOfWeek",is_open AS "isOpen",open_time::text AS "openTime",close_time::text AS "closeTime" FROM store_business_hours WHERE vendor_id=$1 ORDER BY day_of_week`,vendorId);return normalize(rows);}
export async function setHours(userId:string,hours:StoreHour[]){await ensureReady();const vendor=await getVendorProfileForUser(userId);if(hours.length!==7||new Set(hours.map(h=>h.dayOfWeek)).size!==7)throw AppError.badRequest("Business hours must include all seven days.");for(const h of hours){if(h.dayOfWeek<0||h.dayOfWeek>6)throw AppError.badRequest("Invalid business day.");const openTime=h.isOpen?normalizeInputTime(h.openTime):null;const closeTime=h.isOpen?normalizeInputTime(h.closeTime):null;if(h.isOpen&&(!openTime||!closeTime))throw AppError.badRequest(`${DAYS[h.dayOfWeek]} needs valid opening and closing times in HH:MM format.`);await prisma.$executeRawUnsafe(`INSERT INTO store_business_hours(vendor_id,day_of_week,is_open,open_time,close_time,updated_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT(vendor_id,day_of_week) DO UPDATE SET is_open=EXCLUDED.is_open,open_time=EXCLUDED.open_time,close_time=EXCLUDED.close_time,updated_at=NOW()`,vendor.id,h.dayOfWeek,h.isOpen,openTime,closeTime);}return getHours(vendor.id);}
export async function getSetup(userId:string){const vendor=await getVendorProfileForUser(userId);const [products,hasHours]=await Promise.all([prisma.product.count({where:{vendorId:vendor.id,deletedAt:null}}), (async()=>{await ensureReady();const r=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*) AS count FROM store_business_hours WHERE vendor_id=$1 AND is_open=TRUE`,vendor.id);return Number(r[0]?.count??0)>0;})()]);const items=[{key:"store-name",label:"Add your store name",done:Boolean(vendor.storeName?.trim()),href:"/vendor/dashboard/store-settings"},{key:"logo",label:"Add a store logo",done:Boolean(vendor.logoUrl),href:"/vendor/dashboard/store-settings"},{key:"description",label:"Write a clear store description",done:Boolean(vendor.bio?.trim()&&vendor.bio.trim().length>=30),href:"/vendor/dashboard/store-settings"},{key:"location",label:"Add your store location",done:Boolean(vendor.location?.trim()),href:"/vendor/dashboard/store-settings"},{key:"whatsapp",label:"Add a customer contact number",done:Boolean(vendor.whatsappNumber),href:"/vendor/dashboard/store-settings"},{key:"hours",label:"Set your business hours",done:hasHours,href:"/vendor/dashboard/business-hours"},{key:"product",label:"List at least one product",done:products>0,href:"/vendor/dashboard/products/new"}];const completed=items.filter(i=>i.done).length;return{completed,total:items.length,percentage:Math.round(completed/items.length*100),items};}
