import { Router } from "express";
import { z } from "zod";
import { asyncHandler } from "@/middleware/error-handler";
import { requireAuth, requireRole } from "@/middleware/auth";
import * as service from "./store-hours.service";
export const storeHoursRouter=Router();
const hour=z.object({dayOfWeek:z.number().int().min(0).max(6),day:z.string(),isOpen:z.boolean(),openTime:z.string().nullable(),closeTime:z.string().nullable()});
storeHoursRouter.get("/me",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.json({hours:await service.getHours((await import("@/lib/vendor-access")).getVendorProfileForUser? (await (await import("@/lib/vendor-access")).getVendorProfileForUser(req.user!.sub)).id : "")})));
storeHoursRouter.put("/me",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.json({hours:await service.setHours(req.user!.sub,z.array(hour).parse(req.body.hours))})));
storeHoursRouter.get("/setup",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.json(await service.getSetup(req.user!.sub))));
export default storeHoursRouter;
