import { randomBytes } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { recordAudit } from "@/lib/audit";
import { AppError } from "@/utils/app-error";
import { getVendorProfileForUser } from "@/lib/vendor-access";
let storeProfileTablesReady=false;
export const STORE_BADGES=["VERIFIED","BUSINESS","ENTERPRISE","PLATINUM"] as const; export type StoreBadge=(typeof STORE_BADGES)[number]; export const STORE_VISIBILITY=["PUBLIC","PRIVATE","DISPLAY"] as const; export type StoreVisibility=(typeof STORE_VISIBILITY)[number]; const PUBLIC_PROFILE_FIELDS=["headline","description","theme","accentColor","layout","customUrl","visibility"] as const;
function normalizeCustomUrl(value:string|null|undefined){const normalized=(value??"").trim().toLowerCase().replace(/\s+/g,"-").replace(/[^a-z0-9-]/g,"").replace(/-+/g,"-").replace(/^-|-$/g,"");return normalized||null;}
export async function ensureStoreProfileTables(){if(storeProfileTablesReady)return;await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS store_public_profiles (id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL UNIQUE REFERENCES vendor_profiles(id) ON DELETE CASCADE,headline TEXT,description TEXT,theme TEXT NOT NULL DEFAULT 'CLASSIC',accent_color TEXT NOT NULL DEFAULT '#E8622C',layout TEXT NOT NULL DEFAULT 'STANDARD',custom_url TEXT UNIQUE,visibility TEXT NOT NULL DEFAULT 'PUBLIC',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),CHECK (visibility IN ('PUBLIC','PRIVATE','DISPLAY')))`);await prisma.$executeRawUnsafe(`ALTER TABLE store_public_profiles ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'PUBLIC'`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS store_public_profiles_visibility_idx ON store_public_profiles(visibility)`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS store_badges (id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL REFERENCES vendor_profiles(id) ON DELETE CASCADE,badge TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(vendor_id,badge),CHECK (badge IN ('VERIFIED','BUSINESS','ENTERPRISE','PLATINUM')))`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS store_badges_vendor_idx ON store_badges(vendor_id)`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS store_gallery_images (id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL REFERENCES vendor_profiles(id) ON DELETE CASCADE,url TEXT NOT NULL,public_id TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS store_gallery_vendor_idx ON store_gallery_images(vendor_id,position)`);storeProfileTablesReady=true;}
async function getVendorByUserId(userId:string){return getVendorProfileForUser(userId);}
async function getStoreReviewHealth(vendorId:string){
  const cutoff=new Date(Date.now()-90*24*60*60*1000);
  const rows=await prisma.$queryRawUnsafe<Array<{recentReviews:bigint;recentOrders:bigint;problemOrders:bigint;badReviews:bigint}>>(`SELECT COUNT(*) FILTER (WHERE r."createdAt">=$2 AND r.status='VISIBLE') AS "recentReviews", (SELECT COUNT(*) FROM vendor_orders vo WHERE vo.vendor_id=$1 AND vo."createdAt">=$2) AS "recentOrders", (SELECT COUNT(*) FROM vendor_orders vo WHERE vo.vendor_id=$1 AND vo."createdAt">=$2 AND vo.status IN ('CANCELLED','FAILED','REFUNDED')) AS "problemOrders", COUNT(*) FILTER (WHERE r."createdAt">=$2 AND r.status='VISIBLE' AND (r.rating<=2 OR ((CASE WHEN r.delivery_rating='BAD' THEN 1 ELSE 0 END)+(CASE WHEN r.customer_service_rating='BAD' THEN 1 ELSE 0 END)+(CASE WHEN r.product_quality_rating='BAD' THEN 1 ELSE 0 END)+(CASE WHEN r.description_accuracy_rating='BAD' THEN 1 ELSE 0 END)+(CASE WHEN r.value_for_money_rating='BAD' THEN 1 ELSE 0 END))>=2)) AS "badReviews" FROM reviews r INNER JOIN products p ON p.id=r."productId" WHERE p.vendor_id=$1`,vendorId,cutoff);
  const badReviews=Number(rows[0]?.badReviews??0);
  return {windowDays:90,recentReviews:Number(rows[0]?.recentReviews??0),recentOrders:Number(rows[0]?.recentOrders??0),problemOrders:Number(rows[0]?.problemOrders??0),badReviews,caution:badReviews>=3,threshold:3};
} function assertEnterprise(tier:string){if(tier!=="ENTERPRISE")throw AppError.forbidden("Public profile customization is available on the Enterprise plan only");}
export async function getPublicStoreProfile(slug:string){await ensureStoreProfileTables();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT vp.id,vp.store_name AS "storeName",vp.store_slug AS "storeSlug",vp.bio,vp.location,vp.whatsapp_number AS "whatsappNumber",vp.logo_url AS "logoUrl",vp.banner_url AS "bannerUrl",vp.verified,vp.tier,vp.created_at AS "createdAt",vp.view_count AS "viewCount",spp.headline,spp.description,spp.theme,spp.accent_color AS "accentColor",spp.layout,spp.custom_url AS "customUrl",spp.visibility FROM vendor_profiles vp LEFT JOIN store_public_profiles spp ON spp.vendor_id=vp.id WHERE (vp.store_slug=$1 OR spp.custom_url=$1) AND vp.status='APPROVED' AND COALESCE(spp.visibility,'PUBLIC')<>'PRIVATE' LIMIT 1`,slug);const vendor=rows[0];if(!vendor)throw AppError.notFound("Store not found");const[badges,gallery,productCount,reviewHealth]=await Promise.all([prisma.$queryRawUnsafe<Array<{badge:StoreBadge}>>(`SELECT badge FROM store_badges WHERE vendor_id=$1 ORDER BY created_at ASC`,vendor.id),prisma.$queryRawUnsafe<Array<{id:string;url:string;position:number}>>(`SELECT id,url,position FROM store_gallery_images WHERE vendor_id=$1 ORDER BY position ASC,created_at ASC`,vendor.id),prisma.product.count({where:{vendorId:vendor.id,status:"ACTIVE",deletedAt:null}}),getStoreReviewHealth(vendor.id)]);prisma.vendorProfile.update({where:{id:vendor.id},data:{viewCount:{increment:1}}}).catch(()=>undefined);return{...vendor,productCount,badges:badges.map(item=>item.badge),gallery,reviewHealth};}
export async function getMyStoreProfile(userId:string){await ensureStoreProfileTables();const vendor=await getVendorByUserId(userId);const[profileRows,badges,gallery]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT headline,description,theme,accent_color AS "accentColor",layout,custom_url AS "customUrl",visibility FROM store_public_profiles WHERE vendor_id=$1 LIMIT 1`,vendor.id),prisma.$queryRawUnsafe<Array<{badge:StoreBadge}>>(`SELECT badge FROM store_badges WHERE vendor_id=$1 ORDER BY created_at ASC`,vendor.id),prisma.$queryRawUnsafe<Array<{id:string;url:string;publicId:string;position:number}>>(`SELECT id,url,public_id AS "publicId",position FROM store_gallery_images WHERE vendor_id=$1 ORDER BY position ASC,created_at ASC`,vendor.id)]);return{vendorProfile:vendor,profile:profileRows[0]??{headline:null,description:null,theme:"CLASSIC",accentColor:"#E8622C",layout:"STANDARD",customUrl:null,visibility:"PUBLIC"},badges:badges.map(item=>item.badge),gallery,enterprise:vendor.tier==="ENTERPRISE"};}
export async function setMyStoreVisibility(userId:string,visibility:StoreVisibility,ipAddress?:string){await ensureStoreProfileTables();if(!STORE_VISIBILITY.includes(visibility))throw AppError.badRequest("Invalid store visibility");const vendor=await getVendorByUserId(userId);await prisma.$executeRawUnsafe(`INSERT INTO store_public_profiles (id,vendor_id,visibility) VALUES ($1,$2,$3) ON CONFLICT (vendor_id) DO UPDATE SET visibility=EXCLUDED.visibility,updated_at=NOW()`,randomBytes(16).toString("hex"),vendor.id,visibility);await recordAudit({actorId:userId,action:"VENDOR_PROFILE_UPDATED",targetType:"StorePublicProfile",targetId:vendor.id,ipAddress,metadata:{visibility}});return getMyStoreProfile(userId);}
export async function updateMyStoreProfile(userId:string,data:{headline?:string|null;description?:string|null;theme?:string;accentColor?:string;layout?:string;customUrl?:string|null;visibility?:StoreVisibility},ipAddress?:string){await ensureStoreProfileTables();const vendor=await getVendorByUserId(userId);assertEnterprise(vendor.tier);const customUrl=normalizeCustomUrl(data.customUrl);if(customUrl){const conflict=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT id FROM store_public_profiles WHERE custom_url=$1 AND vendor_id<>$2 LIMIT 1`,customUrl,vendor.id);if(conflict[0])throw AppError.conflict("That custom store link is already in use");}if(data.visibility&&!STORE_VISIBILITY.includes(data.visibility))throw AppError.badRequest("Invalid store visibility");await prisma.$executeRawUnsafe(`INSERT INTO store_public_profiles (id,vendor_id,headline,description,theme,accent_color,layout,custom_url,visibility) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (vendor_id) DO UPDATE SET headline=EXCLUDED.headline,description=EXCLUDED.description,theme=EXCLUDED.theme,accent_color=EXCLUDED.accent_color,layout=EXCLUDED.layout,custom_url=EXCLUDED.custom_url,visibility=EXCLUDED.visibility,updated_at=NOW()`,randomBytes(16).toString("hex"),vendor.id,data.headline?.trim()||null,data.description?.trim()||null,data.theme?.trim()||"CLASSIC",data.accentColor?.trim()||"#E8622C",data.layout?.trim()||"STANDARD",customUrl,data.visibility??"PUBLIC");await recordAudit({actorId:userId,action:"VENDOR_PROFILE_UPDATED",targetType:"StorePublicProfile",targetId:vendor.id,ipAddress,metadata:{fields:[...PUBLIC_PROFILE_FIELDS]}});return getMyStoreProfile(userId);}
export async function setBadge(vendorId:string,badge:StoreBadge,enabled:boolean,adminId:string,ipAddress?:string){await ensureStoreProfileTables();const vendor=await prisma.vendorProfile.findUnique({where:{id:vendorId}});if(!vendor)throw AppError.notFound("Vendor profile not found");if(enabled)await prisma.$executeRawUnsafe(`INSERT INTO store_badges (id,vendor_id,badge) VALUES ($1,$2,$3) ON CONFLICT (vendor_id,badge) DO NOTHING`,randomBytes(16).toString("hex"),vendorId,badge);else await prisma.$executeRawUnsafe(`DELETE FROM store_badges WHERE vendor_id=$1 AND badge=$2`,vendorId,badge);if(badge==="VERIFIED")await prisma.vendorProfile.update({where:{id:vendorId},data:{verified:enabled}});await recordAudit({actorId:adminId,action:"VENDOR_PROFILE_UPDATED",targetType:"VendorProfile",targetId:vendorId,ipAddress,metadata:{badge,enabled}});return getAdminStoreProfile(vendorId);}
export async function getAdminStoreProfile(vendorId:string){await ensureStoreProfileTables();const vendor=await prisma.vendorProfile.findUnique({where:{id:vendorId},include:{user:{select:{firstName:true,lastName:true,email:true}}}});if(!vendor)throw AppError.notFound("Vendor profile not found");const badges=await prisma.$queryRawUnsafe<Array<{badge:StoreBadge}>>(`SELECT badge FROM store_badges WHERE vendor_id=$1 ORDER BY created_at ASC`,vendorId);return{...vendor,badges:badges.map(item=>item.badge)};}
export async function getAdminStoreProfiles(){await ensureStoreProfileTables();const vendors=await prisma.vendorProfile.findMany({where:{status:"APPROVED"},include:{user:{select:{firstName:true,lastName:true,email:true}}},orderBy:{storeName:"asc"}});const badges=await prisma.$queryRawUnsafe<Array<{vendor_id:string;badge:StoreBadge}>>(`SELECT vendor_id,badge FROM store_badges ORDER BY created_at ASC`);const badgeMap=new Map<string,StoreBadge[]>();for(const row of badges)badgeMap.set(row.vendor_id,[...(badgeMap.get(row.vendor_id)??[]),row.badge]);return vendors.map(vendor=>({...vendor,badges:badgeMap.get(vendor.id)??[]}));}
export async function deleteGalleryImage(userId:string,imageId:string){await ensureStoreProfileTables();const vendor=await getVendorByUserId(userId);assertEnterprise(vendor.tier);const rows=await prisma.$queryRawUnsafe<Array<{publicId:string}>>(`SELECT public_id AS "publicId" FROM store_gallery_images WHERE id=$1 AND vendor_id=$2 LIMIT 1`,imageId,vendor.id);if(!rows[0])throw AppError.notFound("Gallery image not found");await prisma.$executeRawUnsafe(`DELETE FROM store_gallery_images WHERE id=$1 AND vendor_id=$2`,imageId,vendor.id);return rows[0].publicId;}
export async function addGalleryImage(userId:string,url:string,publicId:string){await ensureStoreProfileTables();const vendor=await getVendorByUserId(userId);assertEnterprise(vendor.tier);const countRows=await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT COUNT(*)::int AS count FROM store_gallery_images WHERE vendor_id=$1`,vendor.id);if((countRows[0]?.count??0)>=12)throw AppError.badRequest("Enterprise stores can have up to 12 gallery images");const positionRows=await prisma.$queryRawUnsafe<Array<{position:number}>>(`SELECT COALESCE(MAX(position),-1)+1 AS position FROM store_gallery_images WHERE vendor_id=$1`,vendor.id);const id=randomBytes(16).toString("hex");await prisma.$executeRawUnsafe(`INSERT INTO store_gallery_images (id,vendor_id,url,public_id,position) VALUES ($1,$2,$3,$4,$5)`,id,vendor.id,url,publicId,positionRows[0]?.position??0);return{id,url,publicId,position:positionRows[0]?.position??0};}
