import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/utils/app-error";
import { getVendorProfileForUser } from "@/lib/vendor-access";
import { queueMaxEvent } from "@/lib/max-event-outbox";
import { notifyProductAvailable } from "@/modules/products/product-availability.service";

async function ensureTable(){await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS launch_campaigns (id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL REFERENCES vendor_profiles(id) ON DELETE CASCADE,product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,launch_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'SCHEDULED',homepage BOOLEAN NOT NULL DEFAULT false,flash_deal_id TEXT,launched_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);}

async function activateProduct(productId:string){const product=await prisma.product.findUnique({where:{id:productId},select:{id:true,comingSoon:true,status:true}});if(!product||product.status!=="ACTIVE"||!product.comingSoon)return;await prisma.product.update({where:{id:product.id},data:{comingSoon:false,availableAt:null}});void notifyProductAvailable(product.id);}

export async function create(userId:string,input:{productId:string;launchAt:string;homepage?:boolean;flashDealId?:string|null}){await ensureTable();const vendor=await getVendorProfileForUser(userId);if(vendor.status!=="APPROVED")throw AppError.forbidden("Your store must be approved before scheduling a launch");const product=await prisma.product.findFirst({where:{id:input.productId,vendorId:vendor.id,deletedAt:null,status:"ACTIVE"}});if(!product)throw AppError.notFound("Active product not found in your store");const launchAt=new Date(input.launchAt);if(!Number.isFinite(launchAt.getTime()))throw AppError.badRequest("Invalid launch time");if(launchAt<=new Date())throw AppError.badRequest("Launch time must be in the future");const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO launch_campaigns(id,vendor_id,product_id,launch_at,status,homepage,flash_deal_id) VALUES($1,$2,$3,$4,'SCHEDULED',$5,$6)`,id,vendor.id,product.id,launchAt,input.homepage??false,input.flashDealId??null);return getMine(userId);}
export async function getMine(userId:string){await ensureTable();const vendor=await getVendorProfileForUser(userId);return prisma.$queryRawUnsafe<any[]>(`SELECT lc.id,lc.product_id AS "productId",p.name,p.slug,p.comingSoon,lc.launch_at AS "launchAt",lc.status,lc.homepage,lc.flash_deal_id AS "flashDealId",lc.launched_at AS "launchedAt" FROM launch_campaigns lc JOIN products p ON p.id=lc.product_id WHERE lc.vendor_id=$1 ORDER BY lc.launch_at DESC`,vendor.id);}
export async function launch(id:string,userId:string){await ensureTable();const vendor=await getVendorProfileForUser(userId);const rows=await prisma.$queryRawUnsafe<any[]>(`UPDATE launch_campaigns SET status='LIVE',launched_at=NOW(),updated_at=NOW() WHERE id=$1 AND vendor_id=$2 AND status='SCHEDULED' RETURNING id,product_id AS "productId",homepage`,id,vendor.id);if(!rows.length)throw AppError.notFound("Scheduled launch not found");await activateProduct(rows[0].productId);void queueMaxEvent("product.launch",{launchCampaignId:id,productId:rows[0].productId,vendorId:vendor.id,homepage:rows[0].homepage});return getMine(userId);}
export async function cancel(id:string,userId:string){await ensureTable();const vendor=await getVendorProfileForUser(userId);const result=await prisma.$executeRawUnsafe(`UPDATE launch_campaigns SET status='CANCELLED',updated_at=NOW() WHERE id=$1 AND vendor_id=$2 AND status='SCHEDULED'`,id,vendor.id);if(!result)throw AppError.notFound("Scheduled launch not found");return getMine(userId);}
export async function activateDue(){await ensureTable();const rows=await prisma.$queryRawUnsafe<any[]>(`UPDATE launch_campaigns SET status='LIVE',launched_at=NOW(),updated_at=NOW() WHERE status='SCHEDULED' AND launch_at<=NOW() RETURNING id,vendor_id AS "vendorId",product_id AS "productId",homepage`);for(const row of rows){await activateProduct(row.productId);void queueMaxEvent("product.launch",{launchCampaignId:row.id,productId:row.productId,vendorId:row.vendorId,homepage:row.homepage});}return rows.length;}
