import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/utils/app-error";
import { getVendorProfileForUser } from "@/lib/vendor-access";
import { recordAudit } from "@/lib/audit";
import { getPlanForTier } from "@/modules/vendor-plans/vendor-plans.service";
import { queueMaxEvent } from "@/lib/max-event-outbox";

async function ensureTable(){await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS flash_deals (id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL REFERENCES vendor_profiles(id) ON DELETE CASCADE,product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,discount_percent NUMERIC(5,2) NOT NULL,sale_price NUMERIC(12,2) NOT NULL,starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,quantity_cap INTEGER,sold_count INTEGER NOT NULL DEFAULT 0,paused BOOLEAN NOT NULL DEFAULT false,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(vendor_id,product_id)); ALTER TABLE flash_deals ADD COLUMN IF NOT EXISTS quantity_cap INTEGER; ALTER TABLE flash_deals ADD COLUMN IF NOT EXISTS sold_count INTEGER NOT NULL DEFAULT 0; ALTER TABLE flash_deals ADD COLUMN IF NOT EXISTS paused BOOLEAN NOT NULL DEFAULT false; CREATE INDEX IF NOT EXISTS flash_deals_active_idx ON flash_deals(active,paused,starts_at,ends_at)`);}

async function soldCounts(ids:string[]){if(!ids.length)return new Map<string,number>();const rows=await prisma.$queryRawUnsafe<Array<{id:string;sold:number}>>(`SELECT fd.id,COALESCE(SUM(oi.quantity),0)::int sold FROM flash_deals fd LEFT JOIN order_items oi ON oi.product_id=fd.product_id LEFT JOIN vendor_orders vo ON vo.id=oi.vendor_order_id LEFT JOIN orders o ON o.id=vo.order_id AND o.payment_status='PAID' WHERE fd.id=ANY($1::text[]) GROUP BY fd.id`,ids);return new Map(rows.map(r=>[r.id,Number(r.sold)]));}

async function deactivateExpired(){await ensureTable();await prisma.$executeRawUnsafe(`UPDATE flash_deals SET active=false,updated_at=NOW() WHERE active=true AND ends_at<=NOW()`);}

export async function listActive(){await deactivateExpired();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT fd.id,fd.product_id AS "productId",fd.vendor_id AS "vendorId",fd.discount_percent AS "discountPercent",fd.sale_price AS "salePrice",fd.starts_at AS "startsAt",fd.ends_at AS "endsAt",fd.quantity_cap AS "quantityCap",fd.sold_count AS "soldCount",fd.paused,p.name,p.slug,p.price,p.stock,v.store_name AS "storeName",v.store_slug AS "storeSlug",v.verified,pi.url AS "imageUrl" FROM flash_deals fd JOIN products p ON p.id=fd.product_id JOIN vendor_profiles v ON v.id=fd.vendor_id LEFT JOIN LATERAL(SELECT url FROM product_images WHERE product_id=p.id ORDER BY position ASC LIMIT 1)pi ON true WHERE fd.active=true AND fd.paused=false AND fd.starts_at<=NOW() AND fd.ends_at>NOW() AND p.status='ACTIVE' AND p.deleted_at IS NULL AND p.coming_soon=false AND v.status='APPROVED' AND(fd.quantity_cap IS NULL OR fd.sold_count<fd.quantity_cap) ORDER BY fd.ends_at ASC`);const counts=await soldCounts(rows.map(r=>r.id));return rows.map(r=>{const sold=Math.max(Number(r.soldCount||0),counts.get(r.id)||0);const cap=r.quantityCap==null?null:Number(r.quantityCap);return{...r,soldCount:sold,remaining:cap==null?null:Math.max(0,cap-sold),progressPercent:cap==null?null:Math.min(100,Math.round(sold/cap*100))};});}

export async function listMine(userId:string){await deactivateExpired();const vendor=await getVendorProfileForUser(userId);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT fd.id,fd.product_id AS "productId",fd.discount_percent AS "discountPercent",fd.sale_price AS "salePrice",fd.starts_at AS "startsAt",fd.ends_at AS "endsAt",fd.quantity_cap AS "quantityCap",fd.sold_count AS "soldCount",fd.paused,fd.active,p.name,p.slug,p.price,p.stock FROM flash_deals fd JOIN products p ON p.id=fd.product_id WHERE fd.vendor_id=$1 ORDER BY fd.created_at DESC`,vendor.id);const counts=await soldCounts(rows.map(r=>r.id));return rows.map(r=>{const sold=Math.max(Number(r.soldCount||0),counts.get(r.id)||0);return{...r,soldCount:sold,remaining:r.quantityCap==null?null:Math.max(0,Number(r.quantityCap)-sold)};});}

function validateDates(a:string,b:string){const s=new Date(a),e=new Date(b);if(!Number.isFinite(s.getTime())||!Number.isFinite(e.getTime())||e<=s)throw AppError.badRequest("Flash deal end time must be after the start time");return{s,e};}
async function access(t:any){if(t==="FREE")throw AppError.forbidden("Flash Deals are available on paid vendor plans. Upgrade to Pro or above to promote products.","FEATURE_REQUIRES_PAID_PLAN");}

async function saveDeal(vendorId:string,input:{productId:string;discountPercent:number;startsAt:Date;endsAt:Date;quantityCap?:number}){const product=await prisma.product.findFirst({where:{id:input.productId,vendorId,deletedAt:null}});if(!product)throw AppError.notFound("Product not found in your store");if(product.comingSoon)throw AppError.badRequest("Coming-soon products cannot be placed in flash deals until they are available");const salePrice=Number(product.price)*(1-input.discountPercent/100);await prisma.$executeRawUnsafe(`INSERT INTO flash_deals(id,vendor_id,product_id,discount_percent,sale_price,starts_at,ends_at,quantity_cap,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) ON CONFLICT(vendor_id,product_id) DO UPDATE SET discount_percent=EXCLUDED.discount_percent,sale_price=EXCLUDED.sale_price,starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at,quantity_cap=EXCLUDED.quantity_cap,paused=false,active=true,updated_at=NOW()`,randomUUID(),vendorId,input.productId,input.discountPercent,salePrice,input.startsAt,input.endsAt,input.quantityCap??null);return{product,salePrice};}

export async function upsert(userId:string,input:{productId:string;discountPercent:number;startsAt:string;endsAt:string;quantityCap?:number}){await ensureTable();const vendor=await getVendorProfileForUser(userId);if(vendor.status!=="APPROVED")throw AppError.forbidden("Your store must be approved before creating flash deals");await access(vendor.tier);const plan=await getPlanForTier(vendor.tier);const existing=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint count FROM flash_deals WHERE vendor_id=$1 AND active=true AND ends_at>NOW() AND paused=false`,vendor.id);const limits:any={PRO:3,BUSINESS:10,ENTERPRISE:25};const limit=limits[vendor.tier]??0;if(Number(existing[0]?.count??0)>=limit)throw AppError.forbidden(`Your ${plan.name} plan allows up to ${limit} active Flash Deals. Upgrade for more promotion capacity.`,"FLASH_DEAL_LIMIT_REACHED");if(input.discountPercent<=0||input.discountPercent>=100)throw AppError.badRequest("Discount must be between 1% and 99%");const{s,e}=validateDates(input.startsAt,input.endsAt);if(input.quantityCap!==undefined&&(!Number.isInteger(input.quantityCap)||input.quantityCap<=0))throw AppError.badRequest("Quantity cap must be a positive whole number");const{product}=await saveDeal(vendor.id,{...input,startsAt:s,endsAt:e});void queueMaxEvent("flash_deal.scheduled",{productId:product.id,productSlug:product.slug,productName:product.name,vendorId:vendor.id,startsAt:s.toISOString(),endsAt:e.toISOString(),discountPercent:input.discountPercent,quantityCap:input.quantityCap??null});return listMine(userId);}

export async function pause(userId:string,id:string,paused:boolean){await ensureTable();const vendor=await getVendorProfileForUser(userId);const result=await prisma.$executeRawUnsafe(`UPDATE flash_deals SET paused=$1,updated_at=NOW() WHERE id=$2 AND vendor_id=$3`,paused,id,vendor.id);if(!result)throw AppError.notFound("Flash deal not found");void queueMaxEvent(paused?"flash_deal.paused":"flash_deal.resumed",{flashDealId:id,vendorId:vendor.id});return{ok:true,paused};}

export async function setQuantityCap(userId:string,id:string,quantityCap:number|null){await ensureTable();const vendor=await getVendorProfileForUser(userId);if(quantityCap!==null&&(!Number.isInteger(quantityCap)||quantityCap<=0))throw AppError.badRequest("Quantity cap must be a positive whole number");const result=await prisma.$executeRawUnsafe(`UPDATE flash_deals SET quantity_cap=$1,updated_at=NOW() WHERE id=$2 AND vendor_id=$3`,quantityCap,id,vendor.id);if(!result)throw AppError.notFound("Flash deal not found");return{ok:true,quantityCap};}

export async function getCheckoutDeals(productIds:string[]){await deactivateExpired();if(!productIds.length)return new Map<string,{salePrice:number;flashDealId:string;quantityCap:number|null;soldCount:number}>();const rows=await prisma.$queryRawUnsafe<Array<{productId:string;salePrice:number;id:string;quantityCap:number|null}>>(`SELECT fd.product_id AS "productId",fd.sale_price AS "salePrice",fd.id,fd.quantity_cap AS "quantityCap" FROM flash_deals fd JOIN products p ON p.id=fd.product_id WHERE fd.product_id=ANY($1::text[]) AND fd.active=true AND fd.paused=false AND fd.starts_at<=NOW() AND fd.ends_at>NOW() AND p.status='ACTIVE' AND p.deleted_at IS NULL AND p.coming_soon=false AND(fd.quantity_cap IS NULL OR fd.sold_count<fd.quantity_cap)`,productIds);const counts=await soldCounts(rows.map(r=>r.id));return new Map(rows.map(r=>[r.productId,{salePrice:Number(r.salePrice),flashDealId:r.id,quantityCap:r.quantityCap==null?null:Number(r.quantityCap),soldCount:counts.get(r.id)||0}]));}

export async function adminCreate(adminId:string,input:{productId:string;discountPercent:number;startsAt:string;endsAt:string;quantityCap?:number}){await ensureTable();const product=await prisma.product.findFirst({where:{id:input.productId,deletedAt:null},select:{id:true,vendorId:true,price:true,comingSoon:true,status:true,slug:true,name:true}});if(!product)throw AppError.notFound("Product not found");if(product.status!=="ACTIVE"||product.comingSoon)throw AppError.badRequest("Only available active products can be placed in flash deals");if(input.discountPercent<=0||input.discountPercent>=100)throw AppError.badRequest("Discount must be between 1% and 99%");const{s,e}=validateDates(input.startsAt,input.endsAt);const salePrice=Number(product.price)*(1-input.discountPercent/100);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO flash_deals(id,vendor_id,product_id,discount_percent,sale_price,starts_at,ends_at,quantity_cap,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) ON CONFLICT(vendor_id,product_id) DO UPDATE SET discount_percent=EXCLUDED.discount_percent,sale_price=EXCLUDED.sale_price,starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at,quantity_cap=EXCLUDED.quantity_cap,paused=false,active=true,updated_at=NOW()`,id,product.vendorId,product.id,input.discountPercent,salePrice,s,e,input.quantityCap??null);await recordAudit({actorId:adminId,action:"ADMIN_FLASH_DEAL_CREATED",targetType:"FlashDeal",targetId:id});void queueMaxEvent("flash_deal.scheduled",{productId:product.id,productSlug:product.slug,productName:product.name,vendorId:product.vendorId,startsAt:s.toISOString(),endsAt:e.toISOString(),discountPercent:input.discountPercent,quantityCap:input.quantityCap??null,createdByAdmin:true});return listActive();}
export async function adminRemove(id:string,adminId:string){await ensureTable();const result=await prisma.$executeRawUnsafe(`DELETE FROM flash_deals WHERE id=$1`,id);if(!result)throw AppError.notFound("Flash deal not found");await recordAudit({actorId:adminId,action:"ADMIN_FLASH_DEAL_CANCELLED",targetType:"FlashDeal",targetId:id});void queueMaxEvent("flash_deal.cancelled",{flashDealId:id,cancelledByAdmin:true});return{ok:true};}
export async function remove(userId:string,id:string){await ensureTable();const vendor=await getVendorProfileForUser(userId);const result=await prisma.$executeRawUnsafe(`DELETE FROM flash_deals WHERE id=$1 AND vendor_id=$2`,id,vendor.id);if(!result)throw AppError.notFound("Flash deal not found");void queueMaxEvent("flash_deal.cancelled",{flashDealId:id,vendorId:vendor.id});return{ok:true};}
export async function getActivePrices(productIds:string[]){const deals=await getCheckoutDeals(productIds);return new Map([...deals.entries()].map(([id,d])=>[id,d.salePrice]));}
