import { Router } from "express";
import { z } from "zod";
import { asyncHandler } from "@/middleware/error-handler";
import { requireAuth, requireRole } from "@/middleware/auth";
import * as service from "./flash-deals.service";
export const flashDealsRouter=Router();
flashDealsRouter.get("/",asyncHandler(async(_req,res)=>res.json({deals:await service.listActive()})));
flashDealsRouter.get("/mine",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.json({deals:await service.listMine(req.user!.sub)})));
const dealSchema=z.object({productId:z.string().uuid(),discountPercent:z.number().positive().max(99),startsAt:z.string().min(1),endsAt:z.string().min(1),quantityCap:z.number().int().positive().optional()});
flashDealsRouter.post("/mine",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.status(201).json({deals:await service.upsert(req.user!.sub,dealSchema.parse(req.body))})));
flashDealsRouter.delete("/mine/:id",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.json(await service.remove(req.user!.sub,req.params.id))));
flashDealsRouter.patch("/mine/:id/pause",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>{const input=z.object({paused:z.boolean()}).parse(req.body);res.json(await service.pause(req.user!.sub,req.params.id,input.paused));}));
flashDealsRouter.patch("/mine/:id/quantity-cap",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>{const input=z.object({quantityCap:z.number().int().positive().nullable()}).parse(req.body);res.json(await service.setQuantityCap(req.user!.sub,req.params.id,input.quantityCap));}));
flashDealsRouter.post("/admin",requireAuth,requireRole("ADMIN"),asyncHandler(async(req,res)=>res.status(201).json({deals:await service.adminCreate(req.user!.sub,dealSchema.parse(req.body))})));
flashDealsRouter.delete("/admin/:id",requireAuth,requireRole("ADMIN"),asyncHandler(async(req,res)=>res.json(await service.adminRemove(req.params.id,req.user!.sub))));
