import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/utils/app-error";
import { getVendorProfileForUser } from "@/lib/vendor-access";
import { recordAudit } from "@/lib/audit";
import { getPlanForTier } from "@/modules/vendor-plans/vendor-plans.service";

async function ensureTable() { await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS flash_deals (id TEXT PRIMARY KEY, vendor_id TEXT NOT NULL REFERENCES vendor_profiles(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, discount_percent NUMERIC(5,2) NOT NULL, sale_price NUMERIC(12,2) NOT NULL, starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(vendor_id, product_id))`); await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS flash_deals_active_idx ON flash_deals(active, starts_at, ends_at)`); }
export async function listActive() { await ensureTable(); return prisma.$queryRawUnsafe<any[]>(`SELECT fd.id, fd.product_id AS "productId", fd.vendor_id AS "vendorId", fd.discount_percent AS "discountPercent", fd.sale_price AS "salePrice", fd.starts_at AS "startsAt", fd.ends_at AS "endsAt", p.name, p.slug, p.price, p.stock, v.store_name AS "storeName", v.store_slug AS "storeSlug", v.verified, pi.url AS "imageUrl" FROM flash_deals fd JOIN products p ON p.id = fd.product_id JOIN vendor_profiles v ON v.id = fd.vendor_id LEFT JOIN LATERAL (SELECT url FROM product_images WHERE product_id = p.id ORDER BY position ASC LIMIT 1) pi ON true WHERE fd.active = true AND fd.starts_at <= NOW() AND fd.ends_at > NOW() AND p.status = 'ACTIVE' AND p.deleted_at IS NULL AND p.coming_soon = false AND v.status = 'APPROVED' ORDER BY fd.ends_at ASC`); }
export async function listMine(userId: string) { await ensureTable(); const vendor = await getVendorProfileForUser(userId); return prisma.$queryRawUnsafe<any[]>(`SELECT fd.id, fd.product_id AS "productId", fd.discount_percent AS "discountPercent", fd.sale_price AS "salePrice", fd.starts_at AS "startsAt", fd.ends_at AS "endsAt", fd.active, p.name, p.price, p.stock FROM flash_deals fd JOIN products p ON p.id = fd.product_id WHERE fd.vendor_id = $1 ORDER BY fd.created_at DESC`, vendor.id); }
function validateDates(startsAtValue: string, endsAtValue: string) { const startsAt = new Date(startsAtValue); const endsAt = new Date(endsAtValue); if (!Number.isFinite(startsAt.getTime()) || !Number.isFinite(endsAt.getTime()) || endsAt <= startsAt) throw AppError.badRequest("Flash deal end time must be after the start time"); return { startsAt, endsAt }; }
async function assertVendorFlashDealAccess(vendorTier: Parameters<typeof getPlanForTier>[0]) { if (vendorTier === "FREE") throw AppError.forbidden("Flash Deals are available on paid vendor plans. Upgrade to Pro or above to promote products.", "FEATURE_REQUIRES_PAID_PLAN"); }
async function saveDeal(vendorId: string, productId: string, discountPercent: number, startsAt: Date, endsAt: Date) { const product = await prisma.product.findFirst({ where: { id: productId, vendorId, deletedAt: null } }); if (!product) throw AppError.notFound("Product not found in your store"); if (product.comingSoon) throw AppError.badRequest("Coming-soon products cannot be placed in flash deals until they are available"); const salePrice = Number(product.price) * (1 - discountPercent / 100); await prisma.$executeRawUnsafe(`INSERT INTO flash_deals (id, vendor_id, product_id, discount_percent, sale_price, starts_at, ends_at, active) VALUES ($1,$2,$3,$4,$5,$6,$7,true) ON CONFLICT (vendor_id, product_id) DO UPDATE SET discount_percent=EXCLUDED.discount_percent, sale_price=EXCLUDED.sale_price, starts_at=EXCLUDED.starts_at, ends_at=EXCLUDED.ends_at, active=true, updated_at=NOW()`, randomUUID(), vendorId, productId, discountPercent, salePrice, startsAt, endsAt); }
export async function upsert(userId: string, input: { productId: string; discountPercent: number; startsAt: string; endsAt: string }) { await ensureTable(); const vendor = await getVendorProfileForUser(userId); if (vendor.status !== "APPROVED") throw AppError.forbidden("Your store must be approved before creating flash deals"); await assertVendorFlashDealAccess(vendor.tier); const plan = await getPlanForTier(vendor.tier); const existing = await prisma.$queryRawUnsafe<Array<{ count: bigint }>>(`SELECT COUNT(*)::bigint AS count FROM flash_deals WHERE vendor_id = $1 AND active = true AND ends_at > NOW()`, vendor.id); const activeCount = Number(existing[0]?.count ?? 0); const limits = { PRO: 3, BUSINESS: 10, ENTERPRISE: 25 } as const; const limit = limits[vendor.tier as keyof typeof limits] ?? 0; if (activeCount >= limit) throw AppError.forbidden(`Your ${plan.name} plan allows up to ${limit} active Flash Deals. Upgrade for more promotion capacity.`, "FLASH_DEAL_LIMIT_REACHED"); if (input.discountPercent <= 0 || input.discountPercent >= 100) throw AppError.badRequest("Discount must be between 1% and 99%"); const { startsAt, endsAt } = validateDates(input.startsAt, input.endsAt); await saveDeal(vendor.id, input.productId, input.discountPercent, startsAt, endsAt); return listMine(userId); }
export async function adminCreate(adminId: string, input: { productId: string; discountPercent: number; startsAt: string; endsAt: string }) { await ensureTable(); const product = await prisma.product.findFirst({ where: { id: input.productId, deletedAt: null }, select: { id: true, vendorId: true, price: true, comingSoon: true, status: true } }); if (!product) throw AppError.notFound("Product not found"); if (product.status !== "ACTIVE") throw AppError.badRequest("Only active products can be placed in flash deals"); if (product.comingSoon) throw AppError.badRequest("Coming-soon products cannot be placed in flash deals until they are available"); if (input.discountPercent <= 0 || input.discountPercent >= 100) throw AppError.badRequest("Discount must be between 1% and 99%"); const { startsAt, endsAt } = validateDates(input.startsAt, input.endsAt); const salePrice = Number(product.price) * (1 - input.discountPercent / 100); const id = randomUUID(); await prisma.$executeRawUnsafe(`INSERT INTO flash_deals (id, vendor_id, product_id, discount_percent, sale_price, starts_at, ends_at, active) VALUES ($1,$2,$3,$4,$5,$6,$7,true) ON CONFLICT (vendor_id, product_id) DO UPDATE SET discount_percent=EXCLUDED.discount_percent, sale_price=EXCLUDED.sale_price, starts_at=EXCLUDED.starts_at, ends_at=EXCLUDED.ends_at, active=true, updated_at=NOW()`, id, product.vendorId, product.id, input.discountPercent, salePrice, startsAt, endsAt); await recordAudit({ actorId: adminId, action: "ADMIN_FLASH_DEAL_CREATED", targetType: "FlashDeal", targetId: id }); return listActive(); }
export async function adminRemove(id: string, adminId: string) { await ensureTable(); const result = await prisma.$executeRawUnsafe(`DELETE FROM flash_deals WHERE id = $1`, id); if (!result) throw AppError.notFound("Flash deal not found"); await recordAudit({ actorId: adminId, action: "ADMIN_FLASH_DEAL_CANCELLED", targetType: "FlashDeal", targetId: id }); return { ok: true }; }
export async function remove(userId: string, id: string) { await ensureTable(); const vendor = await getVendorProfileForUser(userId); const result = await prisma.$executeRawUnsafe(`DELETE FROM flash_deals WHERE id = $1 AND vendor_id = $2`, id, vendor.id); if (!result) throw AppError.notFound("Flash deal not found"); return { ok: true }; }
export async function getActivePrices(productIds: string[]) { await ensureTable(); if (!productIds.length) return new Map<string, number>(); const rows = await prisma.$queryRawUnsafe<Array<{ productId: string; salePrice: number }>>(`SELECT product_id AS "productId", sale_price AS "salePrice" FROM flash_deals WHERE product_id = ANY($1::text[]) AND active = true AND starts_at <= NOW() AND ends_at > NOW()`, productIds); return new Map(rows.map((row) => [row.productId, Number(row.salePrice)])); }
