import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/utils/app-error";
import { recordAudit } from "@/lib/audit";
import { sendEmail, vendorApprovedEmail, vendorRejectedEmail } from "@/lib/email";
import { vendorStoreApprovedWhatsAppMessage } from "@/lib/vendor-whatsapp-notifications";
import { logger } from "@/lib/logger";
import { getVendorProfileForUser } from "@/lib/vendor-access";
import { ensureStoreProfileTables, type StoreBadge } from "@/modules/store-profile/store-profile.service";
import { getPlanForTier } from "@/modules/vendor-plans/vendor-plans.service";

function normalizeStoreSlug(value: string) { return value.trim().toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "").replace(/-+/g, "-").replace(/^-|-$/g, ""); }
export async function getMyVendorProfile(userId: string) { return getVendorProfileForUser(userId); }
export async function updateMyVendorProfile(userId: string, data: { storeName: string; storeSlug: string; bio?: string | null; location?: string | null; whatsappNumber?: string | null }, ipAddress?: string) { const existing = await getVendorProfileForUser(userId); const storeSlug = normalizeStoreSlug(data.storeSlug); if (!storeSlug) throw AppError.badRequest("A valid store URL is required", "INVALID_STORE_SLUG"); const conflict = await prisma.vendorProfile.findFirst({ where: { storeSlug, NOT: { id: existing.id } }, select: { id: true } }); if (conflict) throw AppError.conflict("That store URL is already in use"); const profile = await prisma.vendorProfile.update({ where: { id: existing.id }, data: { storeName: data.storeName, storeSlug, bio: data.bio ?? null, location: data.location ?? null, whatsappNumber: data.whatsappNumber ?? null } }); await recordAudit({ actorId: userId, action: "VENDOR_PROFILE_UPDATED", targetType: "VendorProfile", targetId: profile.id, ipAddress, metadata: { fields: ["storeName", "storeSlug", "bio", "location", "whatsappNumber"] } }); return profile; }
export async function getPublicVendorBySlug(slug: string) { const profile = await prisma.vendorProfile.findUnique({ where: { storeSlug: slug }, select: { id: true, storeName: true, storeSlug: true, bio: true, location: true, whatsappNumber: true, logoUrl: true, bannerUrl: true, verified: true, status: true, createdAt: true, _count: { select: { products: { where: { status: "ACTIVE", deletedAt: null } } } } } }); if (!profile || profile.status !== "APPROVED") throw AppError.notFound("Store not found"); await ensureStoreProfileTables(); const badgeRows = await prisma.$queryRawUnsafe<Array<{ badge: StoreBadge }>>(`SELECT badge FROM store_badges WHERE vendor_id = $1 ORDER BY created_at ASC`, profile.id); prisma.vendorProfile.update({ where: { id: profile.id }, data: { viewCount: { increment: 1 } } }).catch((err: unknown) => logger.error("Failed to increment store view count (non-fatal)", { err })); return { ...profile, badges: badgeRows.map((row) => row.badge) }; }
export async function listPublicVendors(params: { page: number; limit: number; q?: string }) { await ensureStoreProfileTables(); const where = { status: "APPROVED" as const, ...(params.q ? { storeName: { contains: params.q, mode: "insensitive" as const } } : {}) }; const [items, total] = await prisma.$transaction([prisma.vendorProfile.findMany({ where, select: { id: true, storeName: true, storeSlug: true, bio: true, location: true, logoUrl: true, bannerUrl: true, verified: true, tier: true, createdAt: true, _count: { select: { products: { where: { status: "ACTIVE", deletedAt: null } } } } }, orderBy: { createdAt: "desc" }, skip: (params.page - 1) * params.limit, take: params.limit }), prisma.vendorProfile.count({ where })]); const ids = items.map((item) => item.id); const badgeRows = ids.length ? await prisma.$queryRawUnsafe<Array<{ vendor_id: string; badge: StoreBadge }>>(`SELECT vendor_id, badge FROM store_badges WHERE vendor_id = ANY($1::text[]) ORDER BY created_at ASC`, ids) : []; const badgeMap = new Map<string, StoreBadge[]>(); for (const row of badgeRows) badgeMap.set(row.vendor_id, [...(badgeMap.get(row.vendor_id) ?? []), row.badge]); return { stores: items.map((item) => ({ ...item, name: item.storeName, slug: item.storeSlug, productCount: item._count.products, rating: 0, badges: badgeMap.get(item.id) ?? [] })), items, pagination: { page: params.page, limit: params.limit, total, totalPages: Math.max(1, Math.ceil(total / params.limit)) } }; }
export async function listVendorApplications(status?: "PENDING" | "APPROVED" | "REJECTED" | "SUSPENDED") { return prisma.vendorProfile.findMany({ where: status ? { status } : undefined, include: { user: { select: { id: true, firstName: true, lastName: true, email: true } } }, orderBy: { appliedAt: "desc" } }); }
export async function approveVendor(vendorProfileId: string, adminId: string, ipAddress?: string) { await ensureStoreProfileTables(); const profile = await prisma.vendorProfile.update({ where: { id: vendorProfileId }, data: { status: "APPROVED", verified: true, approvedAt: new Date() }, include: { user: true } }); await prisma.$executeRawUnsafe(`INSERT INTO store_badges (id, vendor_id, badge) VALUES ($1, $2, 'VERIFIED') ON CONFLICT (vendor_id, badge) DO NOTHING`, randomUUID(), profile.id); await recordAudit({ actorId: adminId, action: "VENDOR_APPROVED", targetType: "VendorProfile", targetId: profile.id, ipAddress }); void sendEmail({ to: profile.user.email, ...vendorApprovedEmail(profile.storeName) }); if (profile.user.phone) void vendorStoreApprovedWhatsAppMessage(profile.user.phone, profile.storeName).then((result) => { if (!result.delivered) logger.warn("Vendor store approval WhatsApp notification failed", { status: result.status, error: result.error, vendorProfileId: profile.id }); }).catch((error) => logger.warn("Vendor store approval WhatsApp notification threw", { error, vendorProfileId: profile.id })); return profile; }
export async function rejectVendor(vendorProfileId: string, adminId: string, reason: string, ipAddress?: string) { const profile = await prisma.vendorProfile.update({ where: { id: vendorProfileId }, data: { status: "REJECTED", rejectedAt: new Date(), rejectionReason: reason }, include: { user: true } }); await recordAudit({ actorId: adminId, action: "VENDOR_REJECTED", targetType: "VendorProfile", targetId: profile.id, metadata: { reason }, ipAddress }); void sendEmail({ to: profile.user.email, ...vendorRejectedEmail(profile.storeName, reason) }); return profile; }
export async function suspendVendor(vendorProfileId: string, adminId: string, ipAddress?: string) { const profile = await prisma.vendorProfile.update({ where: { id: vendorProfileId }, data: { status: "SUSPENDED" } }); await recordAudit({ actorId: adminId, action: "VENDOR_SUSPENDED", targetType: "VendorProfile", targetId: profile.id, ipAddress }); return profile; }
export async function changeVendorTier(vendorProfileId: string, tier: "FREE" | "PRO" | "BUSINESS" | "ENTERPRISE", adminId: string, ipAddress?: string) { const profile = await prisma.vendorProfile.update({ where: { id: vendorProfileId }, data: { tier } }); await recordAudit({ actorId: adminId, action: "VENDOR_TIER_CHANGED", targetType: "VendorProfile", targetId: profile.id, metadata: { newTier: tier }, ipAddress }); return profile; }
export async function setCommissionOverride(vendorProfileId: string, ratePercent: number | null, adminId: string, ipAddress?: string) { const profile = await prisma.vendorProfile.update({ where: { id: vendorProfileId }, data: { commissionRateOverride: ratePercent } }); await recordAudit({ actorId: adminId, action: "VENDOR_TIER_CHANGED", targetType: "VendorProfile", targetId: vendorProfileId, metadata: { commissionRateOverride: ratePercent }, ipAddress }); return profile; }

/** Admin-granted plan: activates the selected plan without Paystack and can optionally make it lifetime. */
export async function grantVendorSubscription(vendorProfileId: string, tier: "FREE" | "PRO" | "BUSINESS" | "ENTERPRISE", lifetime: boolean, adminId: string, ipAddress?: string) {
  const plan = await getPlanForTier(tier);
  const now = new Date();
  const renewalDate = lifetime ? null : new Date(now.getFullYear(), now.getMonth() + 1, now.getDate(), now.getHours(), now.getMinutes(), now.getSeconds(), now.getMilliseconds());
  await ensureStoreProfileTables();
  const result = await prisma.$transaction(async (tx) => {
    const profile = await tx.vendorProfile.update({ where: { id: vendorProfileId }, data: { tier, verified: true, status: "APPROVED" } });
    const subscription = await tx.vendorSubscription.upsert({ where: { vendorId: vendorProfileId }, create: { vendorId: vendorProfileId, planId: plan.id, status: "ACTIVE", startDate: now, renewalDate, cancelledAt: null }, update: { planId: plan.id, status: "ACTIVE", startDate: now, renewalDate, cancelledAt: null }, include: { plan: true } });
    await tx.$executeRawUnsafe(`INSERT INTO store_badges (id, vendor_id, badge) VALUES ($1, $2, 'VERIFIED') ON CONFLICT (vendor_id, badge) DO NOTHING`, randomUUID(), vendorProfileId);
    if (tier === "ENTERPRISE") await tx.$executeRawUnsafe(`INSERT INTO store_badges (id, vendor_id, badge) VALUES ($1, $2, 'ENTERPRISE') ON CONFLICT (vendor_id, badge) DO NOTHING`, randomUUID(), vendorProfileId);
    return { profile, subscription };
  });
  await recordAudit({ actorId: adminId, action: "VENDOR_TIER_CHANGED", targetType: "VendorSubscription", targetId: result.subscription.id, ipAddress, metadata: { tier, lifetime, adminGranted: true, verified: true } });
  return result;
}
