import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { env } from "@/config/env";
import { AppError } from "@/utils/app-error";
import { initializeTransaction, verifyTransaction } from "@/lib/paystack";
import { recordAudit } from "@/lib/audit";
import { getSettingNumber, SETTING_KEYS } from "@/modules/settings/settings.service";
import { getPlanForTier } from "@/modules/vendor-plans/vendor-plans.service";
import type { FeaturedPlacement, VendorTier } from "@prisma/client";

const PLACEMENT_SETTING_KEY: Record<FeaturedPlacement, string> = { HOMEPAGE: SETTING_KEYS.FEATURED_HOMEPAGE_PRICE_PER_DAY, TRENDING: SETTING_KEYS.FEATURED_TRENDING_PRICE_PER_DAY, CATEGORY: SETTING_KEYS.FEATURED_CATEGORY_PRICE_PER_DAY, SEARCH: SETTING_KEYS.FEATURED_SEARCH_PRICE_PER_DAY };
async function pricePerDayFor(placement: FeaturedPlacement): Promise<number> { return getSettingNumber(PLACEMENT_SETTING_KEY[placement]); }
function priceFor(pricePerDay: number, durationDays: number) { return pricePerDay * durationDays; }
async function assertPaidPromotionAccess(tier: VendorTier) { if (tier === "FREE") throw AppError.forbidden("Featured promotion is available on paid vendor plans. Upgrade to Pro or above.", "FEATURE_REQUIRES_PAID_PLAN"); }
async function assertFeatureCapacity(vendorId: string, tier: VendorTier, kind: "product" | "store") { await assertPaidPromotionAccess(tier); const plan = await getPlanForTier(tier); const limits = kind === "product" ? { PRO: 2, BUSINESS: 8, ENTERPRISE: 20 } : { PRO: 0, BUSINESS: 2, ENTERPRISE: 10 }; const limit = limits[tier as keyof typeof limits] ?? 0; if (!limit) throw AppError.forbidden(`${plan.name} does not include self-service Featured Stores. Upgrade to Business or above.`, "FEATURE_REQUIRES_UPGRADE"); const where = { vendorId, status: "ACTIVE" as const, endDate: { gt: new Date() } }; const count = kind === "product" ? await prisma.featuredProduct.count({ where }) : await prisma.featuredStore.count({ where }); if (count >= limit) throw AppError.forbidden(`Your ${plan.name} plan allows up to ${limit} active featured ${kind}s. Upgrade for more capacity.`, "FEATURE_LIMIT_REACHED"); }
function assertPaidAmount(verification: { amount: number; requested_amount?: number | null; currency: string }, expected: number) { if (verification.currency !== "NGN") throw AppError.badRequest("Payment currency does not match promotion price", "CURRENCY_MISMATCH"); const paidKobo = verification.requested_amount ?? verification.amount; if (Math.round(paidKobo) !== Math.round(expected * 100)) throw AppError.badRequest("Payment amount mismatch", "AMOUNT_MISMATCH"); }

export async function purchaseFeaturedProduct(vendorId: string, vendorEmail: string, input: { productId: string; placement: FeaturedPlacement; durationDays: 1 | 7 | 14 | 30 }) { const product = await prisma.product.findUnique({ where: { id: input.productId } }); if (!product || product.vendorId !== vendorId) throw AppError.forbidden("You can only feature your own products"); const vendor = await prisma.vendorProfile.findUnique({ where: { id: vendorId }, select: { tier: true, status: true } }); if (!vendor || vendor.status !== "APPROVED") throw AppError.forbidden("Your store must be approved before purchasing promotion"); await assertFeatureCapacity(vendorId, vendor.tier, "product"); const price = priceFor(await pricePerDayFor(input.placement), input.durationDays); const reference = `ttfl_feat_prod_${input.productId}_${Date.now()}`; const featured = await prisma.featuredProduct.create({ data: { productId: input.productId, vendorId, placement: input.placement, durationDays: input.durationDays, price, paymentReference: reference, status: "PENDING_PAYMENT" } }); const paystack = await initializeTransaction({ email: vendorEmail, amountNaira: price, reference, callbackUrl: `${env.appUrl}/vendor/dashboard/products/${input.productId}/promote/confirm`, metadata: { featuredProductId: featured.id, kind: "featured_product" } }); return { featured, checkoutUrl: paystack.authorization_url }; }

export async function verifyFeaturedProductPayment(reference: string) { const featured = await prisma.featuredProduct.findUnique({ where: { paymentReference: reference } }); if (!featured) throw AppError.notFound("Featured listing not found"); if (featured.status !== "PENDING_PAYMENT") return featured; const verification = await verifyTransaction(reference); if (["ongoing","pending","processing","queued"].includes(verification.status)) return featured; if (verification.status !== "success") return prisma.featuredProduct.update({ where: { id: featured.id }, data: { status: "CANCELLED" } }); assertPaidAmount(verification, Number(featured.price)); const startDate = new Date(); const endDate = new Date(startDate.getTime() + featured.durationDays * 86400000); return prisma.featuredProduct.update({ where: { id: featured.id }, data: { status: "ACTIVE", startDate, endDate } }); }

export async function handlePaystackFeaturedCharge(reference: string) { const featured = await prisma.featuredProduct.findUnique({ where: { paymentReference: reference } }); if (!featured || featured.status !== "PENDING_PAYMENT") return false; await verifyFeaturedProductPayment(reference); return true; }
export async function getActiveFeaturedProducts(placement: FeaturedPlacement, limit = 10) { return prisma.featuredProduct.findMany({ where: { placement, status: "ACTIVE", endDate: { gt: new Date() }, product: { deletedAt: null, status: "ACTIVE", comingSoon: false } }, include: { product: { include: { images: { orderBy: { position: "asc" } }, vendor: true, category: true } } }, orderBy: { startDate: "desc" }, take: limit }); }
export async function adminCreateFeaturedProduct(adminId: string, input: { productId: string; placement: FeaturedPlacement; durationDays: 1 | 7 | 14 | 30 }) { const product = await prisma.product.findUnique({ where: { id: input.productId } }); if (!product || product.deletedAt) throw AppError.notFound("Product not found"); if (product.status !== "ACTIVE" || product.comingSoon) throw AppError.badRequest("Only available active products can be featured"); const startDate = new Date(); const endDate = new Date(startDate.getTime() + input.durationDays * 86400000); const featured = await prisma.featuredProduct.create({ data: { productId: product.id, vendorId: product.vendorId, placement: input.placement, durationDays: input.durationDays, price: 0, paymentReference: `admin_${randomUUID()}`, status: "ACTIVE", startDate, endDate } }); await recordAudit({ actorId: adminId, action: "ADMIN_FEATURED_PRODUCT_CREATED", targetType: "FeaturedProduct", targetId: featured.id }); return featured; }
export async function adminCancelFeaturedProduct(id: string, adminId: string) { const featured = await prisma.featuredProduct.update({ where: { id }, data: { status: "CANCELLED" } }); await recordAudit({ actorId: adminId, action: "FEATURED_PRODUCT_CANCELLED", targetType: "FeaturedProduct", targetId: id }); return featured; }
export async function purchaseFeaturedStore(vendorId: string, vendorEmail: string, durationDays: 1 | 7 | 14 | 30) { const vendor = await prisma.vendorProfile.findUnique({ where: { id: vendorId }, select: { tier: true, status: true } }); if (!vendor || vendor.status !== "APPROVED") throw AppError.forbidden("Your store must be approved before purchasing promotion"); await assertFeatureCapacity(vendorId, vendor.tier, "store"); const storePricePerDay = await getSettingNumber(SETTING_KEYS.FEATURED_STORE_PRICE_PER_DAY); const price = priceFor(storePricePerDay, durationDays); const reference = `ttfl_feat_store_${vendorId}_${Date.now()}`; const featured = await prisma.featuredStore.create({ data: { vendorId, durationDays, price, paymentReference: reference, status: "PENDING_PAYMENT" } }); const paystack = await initializeTransaction({ email: vendorEmail, amountNaira: price, reference, callbackUrl: `${env.appUrl}/vendor/dashboard/promote-store/confirm`, metadata: { featuredStoreId: featured.id, kind: "featured_store" } }); return { featured, checkoutUrl: paystack.authorization_url }; }

export async function verifyFeaturedStorePayment(reference: string) { const featured = await prisma.featuredStore.findUnique({ where: { paymentReference: reference } }); if (!featured) throw AppError.notFound("Featured store listing not found"); if (featured.status !== "PENDING_PAYMENT") return featured; const verification = await verifyTransaction(reference); if (["ongoing","pending","processing","queued"].includes(verification.status)) return featured; if (verification.status !== "success") return prisma.featuredStore.update({ where: { id: featured.id }, data: { status: "CANCELLED" } }); assertPaidAmount(verification, Number(featured.price)); const startDate = new Date(); const endDate = new Date(startDate.getTime() + featured.durationDays * 86400000); return prisma.featuredStore.update({ where: { id: featured.id }, data: { status: "ACTIVE", startDate, endDate } }); }
export async function handlePaystackFeaturedStoreCharge(reference: string) { const featured = await prisma.featuredStore.findUnique({ where: { paymentReference: reference } }); if (!featured || featured.status !== "PENDING_PAYMENT") return false; await verifyFeaturedStorePayment(reference); return true; }
export async function getActiveFeaturedStores(limit = 10) { return prisma.featuredStore.findMany({ where: { status: "ACTIVE", endDate: { gt: new Date() } }, include: { vendor: true }, orderBy: { startDate: "desc" }, take: limit }); }
export async function adminCreateFeaturedStore(adminId: string, vendorId: string, durationDays: 1 | 7 | 14 | 30) { const vendor = await prisma.vendorProfile.findUnique({ where: { id: vendorId } }); if (!vendor || vendor.status !== "APPROVED") throw AppError.badRequest("Only approved stores can be featured"); const startDate = new Date(); const endDate = new Date(startDate.getTime() + durationDays * 86400000); const featured = await prisma.featuredStore.create({ data: { vendorId, durationDays, price: 0, paymentReference: `admin_${randomUUID()}`, status: "ACTIVE", startDate, endDate } }); await recordAudit({ actorId: adminId, action: "ADMIN_FEATURED_STORE_CREATED", targetType: "FeaturedStore", targetId: featured.id }); return featured; }
export async function adminCancelFeaturedStore(id: string, adminId: string) { const featured = await prisma.featuredStore.update({ where: { id }, data: { status: "CANCELLED" } }); await recordAudit({ actorId: adminId, action: "FEATURED_STORE_CANCELLED", targetType: "FeaturedStore", targetId: id }); return featured; }
