import { Router } from "express";
import { z } from "zod";
import { asyncHandler } from "@/middleware/error-handler";
import { requireAuth, requireRole } from "@/middleware/auth";
import { getVendorProfileForUser } from "@/lib/vendor-access";
import { prisma } from "@/lib/prisma";
import * as featuredService from "./featured.service";

export const featuredRouter = Router();
const durationSchema = z.union([z.literal(1), z.literal(7), z.literal(14), z.literal(30)]);
featuredRouter.get("/products", asyncHandler(async (req, res) => { const placement = (req.query.placement as string)?.toUpperCase() as "HOMEPAGE" | "CATEGORY" | "SEARCH" | "TRENDING"; if (!["HOMEPAGE", "CATEGORY", "SEARCH", "TRENDING"].includes(placement)) return res.status(400).json({ error: { code: "INVALID_PLACEMENT", message: "Invalid placement" } }); res.json({ items: await featuredService.getActiveFeaturedProducts(placement, Number(req.query.limit ?? 10)) }); }));
featuredRouter.get("/stores", asyncHandler(async (req, res) => { res.json({ items: await featuredService.getActiveFeaturedStores(Number(req.query.limit ?? 10)) }); }));
const purchaseProductSchema = z.object({ productId: z.string().uuid(), placement: z.enum(["HOMEPAGE", "CATEGORY", "SEARCH", "TRENDING"]), durationDays: durationSchema });
featuredRouter.post("/products/purchase", requireAuth, requireRole("VENDOR"), asyncHandler(async (req, res) => { const vendor = await getVendorProfileForUser(req.user!.sub); const user = await prisma.user.findUniqueOrThrow({ where: { id: req.user!.sub } }); res.status(201).json(await featuredService.purchaseFeaturedProduct(vendor.id, user.email, purchaseProductSchema.parse(req.body))); }));
featuredRouter.get("/products/verify/:reference", requireAuth, requireRole("VENDOR"), asyncHandler(async (req, res) => { res.json({ featured: await featuredService.verifyFeaturedProductPayment(req.params.reference) }); }));
const purchaseStoreSchema = z.object({ durationDays: durationSchema });
featuredRouter.post("/stores/purchase", requireAuth, requireRole("VENDOR"), asyncHandler(async (req, res) => { const vendor = await getVendorProfileForUser(req.user!.sub); const user = await prisma.user.findUniqueOrThrow({ where: { id: req.user!.sub } }); const { durationDays } = purchaseStoreSchema.parse(req.body); res.status(201).json(await featuredService.purchaseFeaturedStore(vendor.id, user.email, durationDays)); }));
featuredRouter.get("/stores/verify/:reference", requireAuth, requireRole("VENDOR"), asyncHandler(async (req, res) => { res.json({ featured: await featuredService.verifyFeaturedStorePayment(req.params.reference) }); }));
featuredRouter.post("/products/:id/cancel", requireAuth, requireRole("ADMIN"), asyncHandler(async (req, res) => { res.json({ featured: await featuredService.adminCancelFeaturedProduct(req.params.id, req.user!.sub) }); }));
featuredRouter.post("/stores/:id/cancel", requireAuth, requireRole("ADMIN"), asyncHandler(async (req, res) => { res.json({ featured: await featuredService.adminCancelFeaturedStore(req.params.id, req.user!.sub) }); }));
