import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { env } from "@/config/env";
import { AppError } from "@/utils/app-error";
import { sendEmail } from "@/lib/email";
import { renderEmailLayout, escapeHtml } from "@/lib/email-layout";
import { sendWhatsAppTemplate } from "@/lib/whatsapp-notifications";
import { assertComingSoonLimit } from "@/modules/vendor-plans/vendor-plans.service";

export type AvailabilityPreferences = { email?: string; whatsapp?: string; notifyEmail?: boolean; notifyWhatsApp?: boolean };
async function ensureTable() { await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS product_availability_notifications (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, email TEXT, whatsapp TEXT, email_notified_at TIMESTAMPTZ, whatsapp_notified_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CHECK (email IS NOT NULL OR whatsapp IS NOT NULL)`); await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS product_availability_notifications_product_email_idx ON product_availability_notifications(product_id, email) WHERE email IS NOT NULL`); await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS product_availability_notifications_product_whatsapp_idx ON product_availability_notifications(product_id, whatsapp) WHERE whatsapp IS NOT NULL`); await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS product_availability_notifications_product_idx ON product_availability_notifications(product_id)`); }
function normalizePhone(value?: string) { const digits = value?.replace(/\D/g, "") ?? ""; if (!digits) return undefined; if (digits.startsWith("234")) return digits; if (digits.startsWith("0") && digits.length === 11) return `234${digits.slice(1)}`; return digits.length >= 7 ? digits : undefined; }
export async function subscribe(productId: string, userId: string | undefined, preferences: AvailabilityPreferences) { await ensureTable(); const product = await prisma.product.findUnique({ where: { id: productId }, select: { id: true, name: true, slug: true, comingSoon: true, vendorId: true } }); if (!product) throw AppError.notFound("Product not found"); if (!product.comingSoon) throw AppError.badRequest("This product is already available."); const email = preferences.notifyEmail ? preferences.email?.trim().toLowerCase() : undefined; const whatsapp = preferences.notifyWhatsApp ? normalizePhone(preferences.whatsapp) : undefined; if (!email && !whatsapp) throw AppError.badRequest("Choose email or WhatsApp and provide the required contact details."); if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw AppError.badRequest("Please enter a valid email address."); const existing = await prisma.$queryRawUnsafe<Array<{ id: string }>>(`SELECT id FROM product_availability_notifications WHERE product_id = $1 AND ((email IS NOT NULL AND email = $2) OR (whatsapp IS NOT NULL AND whatsapp = $3)) LIMIT 1`, productId, email ?? "", whatsapp ?? ""); if (existing[0]) await prisma.$executeRawUnsafe(`UPDATE product_availability_notifications SET user_id = COALESCE($2, user_id), email = COALESCE($3, email), whatsapp = COALESCE($4, whatsapp), email_notified_at = NULL, whatsapp_notified_at = NULL, updated_at = NOW() WHERE id = $1`, existing[0].id, userId ?? null, email ?? null, whatsapp ?? null); else await prisma.$executeRawUnsafe(`INSERT INTO product_availability_notifications (id, product_id, user_id, email, whatsapp) VALUES ($1,$2,$3,$4,$5)`, randomUUID(), productId, userId ?? null, email ?? null, whatsapp ?? null); return { ok: true, message: "You're on the list. We'll let you know when it becomes available." }; }
export async function notifyProductAvailable(productId: string) { await ensureTable(); const product = await prisma.product.findUnique({ where: { id: productId }, include: { vendor: { select: { storeName: true } } } }); if (!product || product.deletedAt || product.status !== "ACTIVE" || product.comingSoon) return { sent: 0 }; const rows = await prisma.$queryRawUnsafe<Array<{ id: string; email: string | null; whatsapp: string | null; emailNotifiedAt: Date | null; whatsappNotifiedAt: Date | null }>>(`SELECT id, email, whatsapp, email_notified_at AS "emailNotifiedAt", whatsapp_notified_at AS "whatsappNotifiedAt" FROM product_availability_notifications WHERE product_id = $1`, productId); const productUrl = `${env.appUrl}/products/${product.slug}`; let sent = 0; for (const row of rows) { if (row.email && !row.emailNotifiedAt) { try { await sendEmail({ to: row.email, subject: `${product.name} is now available on TTFL Store`, html: renderEmailLayout({ heading: "It's here!", previewText: `${product.name} is now available on TTFL Store.`, bodyHtml: `<p><strong>${escapeHtml(product.name)}</strong> from <strong>${escapeHtml(product.vendor.storeName)}</strong> is now available.</p><p>You asked us to let you know when it launched. You can view it using the button below.</p>`, ctaText: "View product", ctaUrl: productUrl }), event: "product_available" }); await prisma.$executeRawUnsafe(`UPDATE product_availability_notifications SET email_notified_at = NOW(), updated_at = NOW() WHERE id = $1`, row.id); sent += 1; } catch {} } if (row.whatsapp && !row.whatsappNotifiedAt) { let delivered = false; try { const template = await sendWhatsAppTemplate({ to: row.whatsapp, templateName: env.whatsapp.templates.productAvailable, bodyParameters: [product.name], buttonUrlParameters: [product.slug], event: "product_available" }); delivered = Boolean(template.delivered); } catch {} if (delivered) { await prisma.$executeRawUnsafe(`UPDATE product_availability_notifications SET whatsapp_notified_at = NOW(), updated_at = NOW() WHERE id = $1`, row.id); sent += 1; } } }
  const waitlistRows = await prisma.$queryRawUnsafe<Array<{ id: string; email: string | null; whatsapp: string | null }>>(`SELECT id,email,whatsapp FROM product_alerts WHERE product_id=$1 AND type='WAITLIST' AND notified_at IS NULL`, productId);
  for (const row of waitlistRows) {
    let delivered = false;
    if (row.email) { try { await sendEmail({ to: row.email, subject: `${product.name} is now available on TTFL Store`, html: renderEmailLayout({ heading: "It's here!", previewText: `${product.name} is now available on TTFL Store.`, bodyHtml: `<p><strong>${escapeHtml(product.name)}</strong> is now available on TTFL Store.</p><p>You joined the Coming Soon waitlist, so we're letting you know first.</p>`, ctaText: "View product", ctaUrl: productUrl }), event: "product_waitlist_available" }); delivered = true; } catch {} }
    if (row.whatsapp) { try { const result = await sendWhatsAppTemplate({ to: row.whatsapp, templateName: env.whatsapp.templates.productAvailable, bodyParameters: [product.name], buttonUrlParameters: [product.slug], event: "product_waitlist_available" }); delivered = delivered || Boolean(result.delivered); } catch {} }
    if (delivered) { await prisma.$executeRawUnsafe(`UPDATE product_alerts SET notified_at=NOW() WHERE id=$1`, row.id); sent += 1; }
  }
  return { sent }; }
