import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { env } from "@/config/env";
import { AppError } from "@/utils/app-error";
import { slugify } from "@/utils/slugify";
import { recordAudit } from "@/lib/audit";
import { logger } from "@/lib/logger";
import { assertProductLimitNotExceeded, getPlanForTier } from "@/modules/vendor-plans/vendor-plans.service";
import { getVendorProfileForUser } from "@/lib/vendor-access";
import { notifyProductAvailable } from "./product-availability.service";
import { sendEmail, vendorFirstProductEmail } from "@/lib/email";
import { vendorFirstProductWhatsAppMessageTemplate } from "@/lib/vendor-whatsapp-notifications";
import type { CreateProductInput, ProductSearchInput } from "./products.validators";
import type { Prisma } from "@prisma/client";
const PUBLIC_PRODUCT_INCLUDE = { images: { orderBy: { position: "asc" as const } }, category: true, vendor: { select: { id: true, storeName: true, storeSlug: true, verified: true, location: true } } } satisfies Prisma.ProductInclude;
function createPublicProductId() { return `TTFL-${randomUUID().replace(/-/g, "").slice(0, 16).toUpperCase()}`; }
async function getVendorProfileOrThrow(userId: string) { const vendor = await getVendorProfileForUser(userId); if (vendor.status !== "APPROVED") throw AppError.forbidden("Your vendor application needs to be approved before you can list products", "VENDOR_NOT_APPROVED"); return vendor; }
async function uniqueProductSlug(name: string) { const base = slugify(name); let slug = base; let suffix = 1; while (await prisma.product.findUnique({ where: { slug } })) slug = `${base}-${++suffix}`; return slug; }
async function uniquePublicProductId() { let productId = createPublicProductId(); while (await prisma.product.findUnique({ where: { publicProductId: productId } })) productId = createPublicProductId(); return productId; }
async function resolveCategoryId(categorySlug: string) { const category = await prisma.category.findUnique({ where: { slug: categorySlug } }); if (!category) throw AppError.badRequest("Unknown category", "INVALID_CATEGORY"); return category.id; }
const COMING_SOON_LIMITS = { FREE: 3, PRO: 20, BUSINESS: 100, ENTERPRISE: null } as const;
const SPONSORED_LIMITS = { FREE: 0, PRO: 5, BUSINESS: 20, ENTERPRISE: 100 } as const;
async function assertComingSoonCapacity(vendorId: string, tier: keyof typeof COMING_SOON_LIMITS) { const limit = COMING_SOON_LIMITS[tier]; if (limit == null) return; const count = await prisma.product.count({ where: { vendorId, deletedAt: null, comingSoon: true } }); if (count >= limit) throw AppError.forbidden(`Your ${tier} plan allows up to ${limit} active Coming Soon products. Upgrade for more launch capacity.`, "COMING_SOON_LIMIT_REACHED"); }
export async function createProduct(userId: string, input: CreateProductInput) { const vendor = await getVendorProfileOrThrow(userId); await assertProductLimitNotExceeded(vendor.id, vendor.tier); if (input.comingSoon) await assertComingSoonCapacity(vendor.id, vendor.tier); const existingLiveCount = await prisma.product.count({ where: { vendorId: vendor.id, deletedAt: null, status: "ACTIVE" } }); const categoryId = await resolveCategoryId(input.categorySlug); const slug = await uniqueProductSlug(input.name); const publicProductId = await uniquePublicProductId(); const product = await prisma.product.create({ data: { vendorId: vendor.id, categoryId, name: input.name, slug, description: input.description, price: input.price, previousPrice: input.previousPrice, condition: input.condition, stock: input.stock, location: input.location, specifications: input.specifications, estimatedDeliveryDays: input.estimatedDeliveryDays, publicProductId, comingSoon: input.comingSoon ?? false, availableAt: input.availableAt ? new Date(input.availableAt) : undefined, sellingMethod: input.sellingMethod, externalUrl: "externalUrl" in input ? input.externalUrl : undefined, whatsappNumber: "whatsappNumber" in input ? input.whatsappNumber : undefined, images: { create: input.images.map((url, i) => ({ url, position: i, isPrimary: i === 0 })) } }, include: PUBLIC_PRODUCT_INCLUDE }); if (existingLiveCount === 0 && product.status === "ACTIVE" && !product.comingSoon) { const owner = await prisma.user.findUnique({ where: { id: vendor.userId }, select: { email: true, phone: true } }); if (owner?.email) void sendEmail({ to: owner.email, ...vendorFirstProductEmail(vendor.storeName, product.name, `${env.appUrl}/products/${product.slug}`) }).catch(() => undefined); if (owner?.phone) void vendorFirstProductWhatsAppMessageTemplate(owner.phone, product.name, product.slug).then((result) => { if (!result.delivered) logger.warn("Vendor first-product WhatsApp notification failed", { status: result.status, error: result.error, vendorProfileId: vendor.id, productId: product.id }); }).catch((error) => logger.warn("Vendor first-product WhatsApp notification threw", { error, vendorProfileId: vendor.id, productId: product.id })); } return product; }
export async function updateProduct(userId: string, productId: string, input: Partial<CreateProductInput> & { status?: "DRAFT" | "ACTIVE" | "OUT_OF_STOCK" }) { const vendor = await getVendorProfileOrThrow(userId); const existing = await prisma.product.findUnique({ where: { id: productId } }); if (!existing || existing.deletedAt) throw AppError.notFound("Product not found"); if (existing.vendorId !== vendor.id) throw AppError.forbidden("You can only edit your own products"); const categoryId = input.categorySlug ? await resolveCategoryId(input.categorySlug) : undefined; const wasComingSoon = existing.comingSoon; if (!wasComingSoon && input.comingSoon === true) await assertComingSoonCapacity(vendor.id, vendor.tier); const product = await prisma.product.update({ where: { id: productId }, data: { name: input.name, categoryId, description: input.description, price: input.price, previousPrice: input.previousPrice, condition: input.condition, stock: input.stock, location: input.location, specifications: input.specifications, estimatedDeliveryDays: input.estimatedDeliveryDays, status: input.status, comingSoon: input.comingSoon, availableAt: input.availableAt === undefined ? undefined : input.availableAt ? new Date(input.availableAt) : null, sellingMethod: (input as any).sellingMethod, externalUrl: (input as any).externalUrl, whatsappNumber: (input as any).whatsappNumber, ...(input.images ? { images: { deleteMany: {}, create: input.images.map((url, i) => ({ url, position: i, isPrimary: i === 0 })) } } : {}) }, include: PUBLIC_PRODUCT_INCLUDE }); if (wasComingSoon && input.comingSoon === false && product.status === "ACTIVE") void notifyProductAvailable(product.id); return product; }
export async function deleteProduct(userId: string, productId: string) { const vendor = await getVendorProfileOrThrow(userId); const existing = await prisma.product.findUnique({ where: { id: productId } }); if (!existing || existing.deletedAt) throw AppError.notFound("Product not found"); if (existing.vendorId !== vendor.id) throw AppError.forbidden("You can only delete your own products"); await prisma.product.update({ where: { id: productId }, data: { deletedAt: new Date(), sponsored: false, sponsoredAt: null } }); }
export async function listMyProducts(userId: string) { const vendor = await getVendorProfileForUser(userId); return prisma.product.findMany({ where: { vendorId: vendor.id, deletedAt: null }, include: PUBLIC_PRODUCT_INCLUDE, orderBy: { createdAt: "desc" } }); }
export async function getProductBySlug(slug: string) { const product = await prisma.product.findUnique({ where: { slug }, include: PUBLIC_PRODUCT_INCLUDE }); if (!product || product.deletedAt || product.status === "SUSPENDED") throw AppError.notFound("Product not found"); void prisma.product.update({ where: { id: product.id }, data: { viewCount: { increment: 1 } } }); return product; }
async function syncExpiredSponsoredProducts() { try { await prisma.$executeRawUnsafe(`UPDATE products p SET sponsored = false, "sponsoredAt" = NULL WHERE p.sponsored = true AND EXISTS (SELECT 1 FROM vendor_subscriptions vs JOIN vendor_plans vp ON vp.id = vs."planId" WHERE vs."vendorId" = p."vendorId" AND (vs."status" <> 'ACTIVE' OR vp.price <= 0 OR (vs."renewalDate" IS NOT NULL AND vs."renewalDate" <= NOW())))`); } catch (error) { logger.warn("Sponsored product expiry sync skipped; product search will continue", { error }); } }
async function assertActivePaidSubscription(vendorId: string) { const rows = await prisma.$queryRawUnsafe<Array<{ status: string; renewalDate: Date | null; price: number }>>(`SELECT vs."status", vs."renewalDate" AS "renewalDate", vp.price FROM vendor_subscriptions vs JOIN vendor_plans vp ON vp.id = vs."planId" WHERE vs."vendorId" = $1 LIMIT 1`, vendorId); const subscription = rows[0]; if (!subscription || subscription.status !== "ACTIVE" || Number(subscription.price) <= 0 || (subscription.renewalDate && new Date(subscription.renewalDate) <= new Date())) throw AppError.forbidden("Sponsored products are available to vendors with an active paid plan. Upgrade or renew your store subscription to use this feature.", "PAID_PLAN_REQUIRED"); }
export async function listMySponsoredProducts(userId: string) { const vendor = await getVendorProfileOrThrow(userId); await syncExpiredSponsoredProducts(); return prisma.product.findMany({ where: { vendorId: vendor.id, deletedAt: null }, include: PUBLIC_PRODUCT_INCLUDE, orderBy: [{ sponsored: "desc" }, { createdAt: "desc" }] }); }
export async function setProductSponsored(userId: string, productId: string, sponsored: boolean) { const vendor = await getVendorProfileOrThrow(userId); const product = await prisma.product.findFirst({ where: { id: productId, vendorId: vendor.id, deletedAt: null } }); if (!product) throw AppError.notFound("Product not found in your store"); if (sponsored) { await assertActivePaidSubscription(vendor.id); const limit = SPONSORED_LIMITS[vendor.tier]; const count = await prisma.product.count({ where: { vendorId: vendor.id, deletedAt: null, sponsored: true, id: { not: product.id } } }); if (count >= limit) { const plan = await getPlanForTier(vendor.tier); throw AppError.forbidden(`Your ${plan.name} plan allows up to ${limit} sponsored products. Upgrade for more promotion capacity.`, "SPONSORED_LIMIT_REACHED"); } } return prisma.product.update({ where: { id: product.id }, data: { sponsored, sponsoredAt: sponsored ? new Date() : null }, include: PUBLIC_PRODUCT_INCLUDE }); }
function buildOrderBy(sort: ProductSearchInput["sort"]): Prisma.ProductOrderByWithRelationInput { switch (sort) { case "price_asc": return { price: "asc" }; case "price_desc": return { price: "desc" }; case "newest": return { createdAt: "desc" }; case "rating": return { viewCount: "desc" }; default: return { viewCount: "desc" }; } }
function parseMoney(value: string) { const normalized = value.toLowerCase().replace(/₦|,/g, "").trim(); const multiplier = normalized.endsWith("m") ? 1_000_000 : normalized.endsWith("k") ? 1_000 : 1; const numeric = Number(normalized.replace(/[km]$/, "")); return Number.isFinite(numeric) ? numeric * multiplier : undefined; }
function parseNaturalSearch(query?: string) { let text = query?.trim() ?? ""; let minPrice: number | undefined; let maxPrice: number | undefined; let location: string | undefined; const between = text.match(/\bbetween\s+(₦?[\d,.]+\s*[km]?)\s+and\s+(₦?[\d,.]+\s*[km]?)/i); const range = text.match(/(₦?[\d,.]+\s*[km]?)\s*(?:-|–|—|to)\s*(₦?[\d,.]+\s*[km]?)/i); const under = text.match(/\b(?:under|below|less than|up to|max(?:imum)?(?: price)?|at most)\s+(₦?[\d,.]+\s*[km]?)/i); const over = text.match(/\b(?:over|above|more than|from|starting at|minimum(?: price)?)\s+(₦?[\d,.]+\s*[km]?)/i); if (between) { minPrice = parseMoney(between[1]); maxPrice = parseMoney(between[2]); text = text.replace(between[0], " "); } else if (range) { minPrice = parseMoney(range[1]); maxPrice = parseMoney(range[2]); text = text.replace(range[0], " "); } else if (under) { maxPrice = parseMoney(under[1]); text = text.replace(under[0], " "); } else if (over) { minPrice = parseMoney(over[1]); text = text.replace(over[0], " "); } const locationMatch = text.match(/\b(?:in|near)\s+([a-z][a-z\s-]{1,50}?)(?=\s+(?:for\s+sale|under|below|above|over|between|from|starting|with|price|₦|\d)|$)/i); if (locationMatch) { location = locationMatch[1].trim().replace(/\s+/g, " "); text = text.replace(locationMatch[0], " "); } text = text.replace(/\bfor\s+sale\b/gi, " ").replace(/\b(?:buy|purchase|available|looking\s+for|show\s+me|find|cheap|best|deals?|prices?)\b/gi, " ").replace(/\s+/g, " ").trim(); return { text, location, minPrice, maxPrice }; }
export async function searchProducts(params: ProductSearchInput) { await syncExpiredSponsoredProducts(); const parsed = parseNaturalSearch(params.q); const location = params.location?.trim() || parsed.location; const minPrice = params.minPrice ?? parsed.minPrice; const maxPrice = params.maxPrice ?? parsed.maxPrice; const where: Prisma.ProductWhereInput = { deletedAt: null, status: "ACTIVE" }; if (parsed.text) { const tokens = Array.from(new Set(parsed.text.toLowerCase().split(/\s+/).map((token) => token.trim()).filter(Boolean))).slice(0, 8); const tokenFilters: Prisma.ProductWhereInput[] = tokens.flatMap((token) => [{ name: { contains: token, mode: "insensitive" } }, { description: { contains: token, mode: "insensitive" } }, { vendor: { storeName: { contains: token, mode: "insensitive" } } }, { vendor: { storeSlug: { contains: token, mode: "insensitive" } } }]); if (tokenFilters.length) where.OR = tokenFilters; } if (params.category) where.category = { slug: params.category }; if (params.condition) where.condition = params.condition; if (params.sellingMethod) where.sellingMethod = params.sellingMethod; if (location) where.AND = [{ OR: [{ location: { contains: location, mode: "insensitive" } }, { vendor: { location: { contains: location, mode: "insensitive" } } }] }]; if (params.vendor || params.verifiedOnly) { const vendorFilter: Prisma.VendorProfileWhereInput = {}; if (params.vendor) vendorFilter.storeSlug = params.vendor; if (params.verifiedOnly) vendorFilter.verified = true; where.vendor = { is: vendorFilter }; } if (minPrice !== undefined || maxPrice !== undefined) where.price = { ...(minPrice !== undefined ? { gte: minPrice } : {}), ...(maxPrice !== undefined ? { lte: maxPrice } : {}) }; const [items, total] = await prisma.$transaction([prisma.product.findMany({ where, include: PUBLIC_PRODUCT_INCLUDE, orderBy: [{ sponsored: "desc" }, buildOrderBy(params.sort)], skip: (params.page - 1) * params.limit, take: params.limit }), prisma.product.count({ where })]); return { items, pagination: { page: params.page, limit: params.limit, total, totalPages: Math.max(1, Math.ceil(total / params.limit)) } }; }
export async function recordReferralAndGetDestination(productId: string, meta: { sessionId?: string; source?: string; userAgent?: string; ipAddress?: string; deviceType?: string; campaign?: string }) { const product = await prisma.product.findUnique({ where: { id: productId }, include: { vendor: true } }); if (!product || product.deletedAt) throw AppError.notFound("Product not found"); let destination: string; let type: "EXTERNAL_CLICK" | "WHATSAPP_CLICK"; if (product.sellingMethod === "EXTERNAL_LINK") { if (!product.externalUrl) throw AppError.internal("Product is missing its external URL"); destination = product.externalUrl; type = "EXTERNAL_CLICK"; } else if (product.sellingMethod === "WHATSAPP") { const number = product.whatsappNumber ?? product.vendor.whatsappNumber; if (!number) throw AppError.internal("Product is missing a WhatsApp number"); const message = encodeURIComponent(`Hi, I'm interested in "${product.name}" (${env.appUrl}/products/${product.slug})`); destination = `https://wa.me/${number.replace(/\D/g, "")}?text=${message}`; type = "WHATSAPP_CLICK"; } else throw AppError.badRequest("This product uses TTFL Store checkout, not an external referral"); await prisma.referralEvent.create({ data: { vendorId: product.vendorId, productId: product.id, type, sessionId: meta.sessionId, source: meta.source, destination, userAgent: meta.userAgent, deviceType: meta.deviceType, ipAddress: meta.ipAddress, campaign: meta.campaign } }); return { destination }; }
export async function adminListProducts(params: { q?: string; page: number; limit: number }) { const where: Prisma.ProductWhereInput = { deletedAt: null }; if (params.q) where.OR = [{ name: { contains: params.q, mode: "insensitive" } }, { vendor: { storeName: { contains: params.q, mode: "insensitive" } } }]; const [items, total] = await prisma.$transaction([prisma.product.findMany({ where, include: PUBLIC_PRODUCT_INCLUDE, orderBy: { createdAt: "desc" }, skip: (params.page - 1) * params.limit, take: params.limit }), prisma.product.count({ where })]); return { items, pagination: { page: params.page, limit: params.limit, total, pages: Math.max(1, Math.ceil(total / params.limit)) } }; }
export async function suspendProduct(productId: string, adminId: string, ipAddress?: string) { const product = await prisma.product.update({ where: { id: productId }, data: { status: "SUSPENDED" } }); await recordAudit({ actorId: adminId, action: "PRODUCT_SUSPENDED", targetType: "Product", targetId: product.id, ipAddress }); return product; }
export async function reinstateProduct(productId: string, adminId: string, ipAddress?: string) { const product = await prisma.product.update({ where: { id: productId }, data: { status: "ACTIVE" } }); await recordAudit({ actorId: adminId, action: "PRODUCT_REINSTATED", targetType: "Product", targetId: product.id, ipAddress }); return product; }
