import { Router } from "express";
import { z } from "zod";
import { asyncHandler } from "@/middleware/error-handler";
import { requireAuth, requireRole } from "@/middleware/auth";
import { recordEvent, vendorReport, adminReport } from "./promotion-analytics.service";
export const promotionAnalyticsRouter=Router();
const eventSchema=z.object({promotionType:z.enum(["FLASH_DEAL","FEATURED_PRODUCT","FEATURED_STORE","SPONSORED_PRODUCT"]),promotionId:z.string().min(1).max(100),vendorId:z.string().min(1).max(100),productId:z.string().max(100).optional(),event:z.enum(["VIEW","CLICK","ADD_TO_CART","ORDER"]),sessionId:z.string().max(200).optional(),userId:z.string().max(100).optional(),quantity:z.number().int().positive().optional(),revenue:z.number().nonnegative().optional(),source:z.string().max(100).optional()});
promotionAnalyticsRouter.post("/event",asyncHandler(async(req,res)=>res.status(201).json(await recordEvent(eventSchema.parse(req.body)))));
promotionAnalyticsRouter.get("/mine",requireAuth,requireRole("VENDOR"),asyncHandler(async(req,res)=>res.json(await vendorReport(req.user!.sub))));
 promotionAnalyticsRouter.get("/admin",requireAuth,requireRole("ADMIN"),asyncHandler(async(_req,res)=>res.json(await adminReport())));
